language: R
cache: packages
git:
  submodules: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
env:
  global:
  - CXX=g++-8
before_script:
- mkdir -p ~/.R
- echo "CXX = $CXX" > ~/.R/Makevars
- echo "CXX14 = $CXX" >> ~/.R/Makevars
- echo "CXX14FLAGS = $(R CMD config CXXFLAGS) -fPIC" >> ~/.R/Makevars
