test_that("generator functions work", {
  n = 8L
  edges = seq_len(n)
  el = matrix(as.numeric(edges), ncol = 2L)
  symeli = matrix(edges, ncol = 2L)
  symelc = matrix(as.character(edges), ncol = 2L)
  dfi = as.data.frame(symeli)
  dfc = as.data.frame(symelc)
  expect_s4_class(graph_tree(n), "Rcpp_IGraph")
  expect_s4_class(graph_create(edges), "Rcpp_IGraph")
  expect_s4_class(graph_from_edgelist(el), "Rcpp_IGraph")
  expect_type(graph_from_symbolic_edgelist(symeli)$Vattr$name, "integer")
  expect_type(graph_from_symbolic_edgelist(symelc)$Vattr$name, "character")
  expect_type(graph_from_data_frame(dfi)$Vattr$name, "integer")
  expect_type(graph_from_data_frame(dfc)$Vattr$name, "character")
  expect_error(graph_create(seq_len(n - 1L)))
})

test_that("as_/is_ functions work", {
  n = 8L
  edges = seq_len(n)
  el = matrix(as.numeric(edges), ncol = 2L)
  symel = matrix(edges, ncol = 2L)
  df = as.data.frame(el)
  expect_false(is_igraph(df))
  expect_true(is_igraph(as_igraph(edges)))
  expect_true(is_igraph(as_igraph(el)))
  expect_true(is_igraph(as_igraph(symel)))
  expect_true(is_igraph(as_igraph(df)))
})
