test_that("layout functions return x-y columns", {
  g = graph_tree(7L)
  expect_named(layout_random(g), c("x", "y"))
  expect_named(layout_nicely(g), c("x", "y"))
  expect_named(layout_drl(g), c("x", "y"))
  expect_named(layout_fruchterman_reingold(g), c("x", "y"))
  expect_named(layout_mds(g, distances(g)), c("x", "y"))
  expect_named(layout_reingold_tilford(g), c("x", "y"))
  expect_named(layout_reingold_tilford_circular(g), c("x", "y"))
})

test_that("layout_random() generates consistent numbers", {
  skip("cannot be seeded if igraph is built as a static library")
  g = graph_tree(7L)
  expect_silent(igraph_rng_seed(19937L))
  l1 = layout_random(g)
  expect_silent(igraph_rng_seed(19937L))
  l2 = layout_random(g)
  expect_identical(l1, l2)
})
