// Generated by cpp11: do not edit by hand
// clang-format off

#include "igraphlite_types.h"
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// attributes.cpp
SEXP V_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_V_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(V_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// attributes.cpp
SEXP E_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_E_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(E_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// attributes.cpp
SEXP Vnames_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_Vnames_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(Vnames_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// attributes.cpp
SEXP from_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_from_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(from_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// attributes.cpp
SEXP to_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_to_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(to_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// attributes.cpp
SEXP getVattr_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_getVattr_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(getVattr_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// attributes.cpp
SEXP getEattr_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_getEattr_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(getEattr_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// attributes.cpp
void setVattr_(cpp11::external_pointer<IGraph> graph, SEXP other);
extern "C" SEXP _igraphlite_setVattr_(SEXP graph, SEXP other) {
  BEGIN_CPP11
    setVattr_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<SEXP>>(other));
    return R_NilValue;
  END_CPP11
}
// attributes.cpp
void setEattr_(cpp11::external_pointer<IGraph> graph, SEXP other);
extern "C" SEXP _igraphlite_setEattr_(SEXP graph, SEXP other) {
  BEGIN_CPP11
    setEattr_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<SEXP>>(other));
    return R_NilValue;
  END_CPP11
}
// attributes.cpp
void mutate_Vattr_(cpp11::external_pointer<IGraph> graph, const char* key, SEXP value);
extern "C" SEXP _igraphlite_mutate_Vattr_(SEXP graph, SEXP key, SEXP value) {
  BEGIN_CPP11
    mutate_Vattr_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const char*>>(key), cpp11::as_cpp<cpp11::decay_t<SEXP>>(value));
    return R_NilValue;
  END_CPP11
}
// attributes.cpp
void mutate_Eattr_(cpp11::external_pointer<IGraph> graph, const char* key, SEXP value);
extern "C" SEXP _igraphlite_mutate_Eattr_(SEXP graph, SEXP key, SEXP value) {
  BEGIN_CPP11
    mutate_Eattr_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const char*>>(key), cpp11::as_cpp<cpp11::decay_t<SEXP>>(value));
    return R_NilValue;
  END_CPP11
}
// basic.cpp
SEXP graph_empty_(int n, bool directed);
extern "C" SEXP _igraphlite_graph_empty_(SEXP n, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_empty_(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}
// basic.cpp
SEXP graph_copy_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_graph_copy_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_copy_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// basic.cpp
int vcount_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_vcount_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(vcount_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// basic.cpp
int ecount_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_ecount_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(ecount_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// basic.cpp
bool is_directed_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_is_directed_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_directed_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// basic.cpp
SEXP edge_(const cpp11::external_pointer<IGraph> graph, int eid);
extern "C" SEXP _igraphlite_edge_(SEXP graph, SEXP eid) {
  BEGIN_CPP11
    return cpp11::as_sexp(edge_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<int>>(eid)));
  END_CPP11
}
// basic.cpp
SEXP edges_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& eids, const bool bycol);
extern "C" SEXP _igraphlite_edges_(SEXP graph, SEXP eids, SEXP bycol) {
  BEGIN_CPP11
    return cpp11::as_sexp(edges_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(eids), cpp11::as_cpp<cpp11::decay_t<const bool>>(bycol)));
  END_CPP11
}
// basic.cpp
SEXP get_eids_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& pairs, const bool directed, const bool error);
extern "C" SEXP _igraphlite_get_eids_(SEXP graph, SEXP pairs, SEXP directed, SEXP error) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_eids_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(pairs), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const bool>>(error)));
  END_CPP11
}
// basic.cpp
SEXP get_all_eids_between_(const cpp11::external_pointer<IGraph> graph, int from, int to, const bool directed);
extern "C" SEXP _igraphlite_get_all_eids_between_(SEXP graph, SEXP from, SEXP to, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_all_eids_between_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<int>>(from), cpp11::as_cpp<cpp11::decay_t<int>>(to), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed)));
  END_CPP11
}
// basic.cpp
SEXP neighbors_(const cpp11::external_pointer<IGraph> graph, int node, const int mode, int loops, bool multiple);
extern "C" SEXP _igraphlite_neighbors_(SEXP graph, SEXP node, SEXP mode, SEXP loops, SEXP multiple) {
  BEGIN_CPP11
    return cpp11::as_sexp(neighbors_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<int>>(node), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<int>>(loops), cpp11::as_cpp<cpp11::decay_t<bool>>(multiple)));
  END_CPP11
}
// basic.cpp
SEXP incident_(const cpp11::external_pointer<IGraph> graph, int node, const int mode, const int loops);
extern "C" SEXP _igraphlite_incident_(SEXP graph, SEXP node, SEXP mode, SEXP loops) {
  BEGIN_CPP11
    return cpp11::as_sexp(incident_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<int>>(node), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<const int>>(loops)));
  END_CPP11
}
// basic.cpp
SEXP degree_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids, const int mode, const int loops);
extern "C" SEXP _igraphlite_degree_(SEXP graph, SEXP vids, SEXP mode, SEXP loops) {
  BEGIN_CPP11
    return cpp11::as_sexp(degree_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<const int>>(loops)));
  END_CPP11
}
// basic.cpp
bool is_same_graph_(const cpp11::external_pointer<IGraph> graph1, const cpp11::external_pointer<IGraph> graph2);
extern "C" SEXP _igraphlite_is_same_graph_(SEXP graph1, SEXP graph2) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_same_graph_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph1), cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph2)));
  END_CPP11
}
// basic.cpp
void add_vertices_(cpp11::external_pointer<IGraph> graph, int n);
extern "C" SEXP _igraphlite_add_vertices_(SEXP graph, SEXP n) {
  BEGIN_CPP11
    add_vertices_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<int>>(n));
    return R_NilValue;
  END_CPP11
}
// basic.cpp
void add_edges_(cpp11::external_pointer<IGraph> graph, const cpp11::integers& edges);
extern "C" SEXP _igraphlite_add_edges_(SEXP graph, SEXP edges) {
  BEGIN_CPP11
    add_edges_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(edges));
    return R_NilValue;
  END_CPP11
}
// basic.cpp
void delete_edges_(cpp11::external_pointer<IGraph> graph, const cpp11::integers& eids);
extern "C" SEXP _igraphlite_delete_edges_(SEXP graph, SEXP eids) {
  BEGIN_CPP11
    delete_edges_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(eids));
    return R_NilValue;
  END_CPP11
}
// basic.cpp
void delete_vertices_(cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids);
extern "C" SEXP _igraphlite_delete_vertices_(SEXP graph, SEXP vids) {
  BEGIN_CPP11
    delete_vertices_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids));
    return R_NilValue;
  END_CPP11
}
// basic.cpp
int VCOUNT_MAX();
extern "C" SEXP _igraphlite_VCOUNT_MAX() {
  BEGIN_CPP11
    return cpp11::as_sexp(VCOUNT_MAX());
  END_CPP11
}
// basic.cpp
int ECOUNT_MAX();
extern "C" SEXP _igraphlite_ECOUNT_MAX() {
  BEGIN_CPP11
    return cpp11::as_sexp(ECOUNT_MAX());
  END_CPP11
}
// basic.cpp
int UNLIMITED();
extern "C" SEXP _igraphlite_UNLIMITED() {
  BEGIN_CPP11
    return cpp11::as_sexp(UNLIMITED());
  END_CPP11
}
// centrality.cpp
SEXP closeness_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids, const int mode, const cpp11::doubles& weights, const bool normalized);
extern "C" SEXP _igraphlite_closeness_(SEXP graph, SEXP vids, SEXP mode, SEXP weights, SEXP normalized) {
  BEGIN_CPP11
    return cpp11::as_sexp(closeness_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const bool>>(normalized)));
  END_CPP11
}
// centrality.cpp
SEXP harmonic_centrality_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids, const int mode, const cpp11::doubles& weights, const bool normalized);
extern "C" SEXP _igraphlite_harmonic_centrality_(SEXP graph, SEXP vids, SEXP mode, SEXP weights, SEXP normalized) {
  BEGIN_CPP11
    return cpp11::as_sexp(harmonic_centrality_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const bool>>(normalized)));
  END_CPP11
}
// centrality.cpp
SEXP betweenness_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, const cpp11::integers& vids, const bool directed, const bool normalized, const double cutoff);
extern "C" SEXP _igraphlite_betweenness_(SEXP graph, SEXP weights, SEXP vids, SEXP directed, SEXP normalized, SEXP cutoff) {
  BEGIN_CPP11
    return cpp11::as_sexp(betweenness_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const bool>>(normalized), cpp11::as_cpp<cpp11::decay_t<const double>>(cutoff)));
  END_CPP11
}
// centrality.cpp
SEXP betweenness_subset_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, const cpp11::integers& sources, const cpp11::integers& targets, const cpp11::integers& vids, const bool directed, const bool normalized);
extern "C" SEXP _igraphlite_betweenness_subset_(SEXP graph, SEXP weights, SEXP sources, SEXP targets, SEXP vids, SEXP directed, SEXP normalized) {
  BEGIN_CPP11
    return cpp11::as_sexp(betweenness_subset_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(sources), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(targets), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const bool>>(normalized)));
  END_CPP11
}
// centrality.cpp
SEXP edge_betweenness_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, const cpp11::integers& eids, const bool directed, const bool normalized, const double cutoff);
extern "C" SEXP _igraphlite_edge_betweenness_(SEXP graph, SEXP weights, SEXP eids, SEXP directed, SEXP normalized, SEXP cutoff) {
  BEGIN_CPP11
    return cpp11::as_sexp(edge_betweenness_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(eids), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const bool>>(normalized), cpp11::as_cpp<cpp11::decay_t<const double>>(cutoff)));
  END_CPP11
}
// centrality.cpp
SEXP edge_betweenness_subset_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, const cpp11::integers& sources, const cpp11::integers& targets, const cpp11::integers& eids, const bool directed, const bool normalized);
extern "C" SEXP _igraphlite_edge_betweenness_subset_(SEXP graph, SEXP weights, SEXP sources, SEXP targets, SEXP eids, SEXP directed, SEXP normalized) {
  BEGIN_CPP11
    return cpp11::as_sexp(edge_betweenness_subset_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(sources), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(targets), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(eids), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const bool>>(normalized)));
  END_CPP11
}
// centrality.cpp
SEXP pagerank_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, const cpp11::doubles& reset, const double damping, const bool directed, const cpp11::integers& vids);
extern "C" SEXP _igraphlite_pagerank_(SEXP graph, SEXP weights, SEXP reset, SEXP damping, SEXP directed, SEXP vids) {
  BEGIN_CPP11
    return cpp11::as_sexp(pagerank_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(reset), cpp11::as_cpp<cpp11::decay_t<const double>>(damping), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids)));
  END_CPP11
}
// centrality.cpp
SEXP constraint_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids, const cpp11::doubles& weights);
extern "C" SEXP _igraphlite_constraint_(SEXP graph, SEXP vids, SEXP weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(constraint_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights)));
  END_CPP11
}
// centrality.cpp
SEXP eigenvector_centrality_(const cpp11::external_pointer<IGraph> graph, const int mode, const cpp11::doubles& weights);
extern "C" SEXP _igraphlite_eigenvector_centrality_(SEXP graph, SEXP mode, SEXP weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(eigenvector_centrality_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights)));
  END_CPP11
}
// centrality.cpp
SEXP hub_and_authority_scores_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights);
extern "C" SEXP _igraphlite_hub_and_authority_scores_(SEXP graph, SEXP weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(hub_and_authority_scores_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights)));
  END_CPP11
}
// centrality.cpp
SEXP convergence_degree_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_convergence_degree_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(convergence_degree_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// cliques.cpp
SEXP cliques_(const cpp11::external_pointer<IGraph> graph, const int min_size, const int max_size, const int max_results);
extern "C" SEXP _igraphlite_cliques_(SEXP graph, SEXP min_size, SEXP max_size, SEXP max_results) {
  BEGIN_CPP11
    return cpp11::as_sexp(cliques_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(min_size), cpp11::as_cpp<cpp11::decay_t<const int>>(max_size), cpp11::as_cpp<cpp11::decay_t<const int>>(max_results)));
  END_CPP11
}
// cliques.cpp
SEXP clique_size_hist_(const cpp11::external_pointer<IGraph> graph, const int min_size, const int max_size);
extern "C" SEXP _igraphlite_clique_size_hist_(SEXP graph, SEXP min_size, SEXP max_size) {
  BEGIN_CPP11
    return cpp11::as_sexp(clique_size_hist_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(min_size), cpp11::as_cpp<cpp11::decay_t<const int>>(max_size)));
  END_CPP11
}
// cliques.cpp
SEXP largest_cliques_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_largest_cliques_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(largest_cliques_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// cliques.cpp
SEXP maximal_cliques_(const cpp11::external_pointer<IGraph> graph, const int min_size, const int max_size, const int max_results);
extern "C" SEXP _igraphlite_maximal_cliques_(SEXP graph, SEXP min_size, SEXP max_size, SEXP max_results) {
  BEGIN_CPP11
    return cpp11::as_sexp(maximal_cliques_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(min_size), cpp11::as_cpp<cpp11::decay_t<const int>>(max_size), cpp11::as_cpp<cpp11::decay_t<const int>>(max_results)));
  END_CPP11
}
// cliques.cpp
int maximal_cliques_count_(const cpp11::external_pointer<IGraph> graph, const int min_size, const int max_size);
extern "C" SEXP _igraphlite_maximal_cliques_count_(SEXP graph, SEXP min_size, SEXP max_size) {
  BEGIN_CPP11
    return cpp11::as_sexp(maximal_cliques_count_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(min_size), cpp11::as_cpp<cpp11::decay_t<const int>>(max_size)));
  END_CPP11
}
// cliques.cpp
SEXP maximal_cliques_hist_(const cpp11::external_pointer<IGraph> graph, const int min_size, const int max_size);
extern "C" SEXP _igraphlite_maximal_cliques_hist_(SEXP graph, SEXP min_size, SEXP max_size) {
  BEGIN_CPP11
    return cpp11::as_sexp(maximal_cliques_hist_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(min_size), cpp11::as_cpp<cpp11::decay_t<const int>>(max_size)));
  END_CPP11
}
// cliques.cpp
int clique_number_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_clique_number_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(clique_number_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// cliques.cpp
SEXP independent_vertex_sets_(const cpp11::external_pointer<IGraph> graph, const int min_size, const int max_size, const int max_results);
extern "C" SEXP _igraphlite_independent_vertex_sets_(SEXP graph, SEXP min_size, SEXP max_size, SEXP max_results) {
  BEGIN_CPP11
    return cpp11::as_sexp(independent_vertex_sets_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(min_size), cpp11::as_cpp<cpp11::decay_t<const int>>(max_size), cpp11::as_cpp<cpp11::decay_t<const int>>(max_results)));
  END_CPP11
}
// cliques.cpp
SEXP largest_independent_vertex_sets_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_largest_independent_vertex_sets_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(largest_independent_vertex_sets_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// cliques.cpp
SEXP maximal_independent_vertex_sets_(const cpp11::external_pointer<IGraph> graph, const int min_size, const int max_size, const int max_results);
extern "C" SEXP _igraphlite_maximal_independent_vertex_sets_(SEXP graph, SEXP min_size, SEXP max_size, SEXP max_results) {
  BEGIN_CPP11
    return cpp11::as_sexp(maximal_independent_vertex_sets_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(min_size), cpp11::as_cpp<cpp11::decay_t<const int>>(max_size), cpp11::as_cpp<cpp11::decay_t<const int>>(max_results)));
  END_CPP11
}
// cliques.cpp
int independence_number_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_independence_number_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(independence_number_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// components.cpp
SEXP connected_components_(const cpp11::external_pointer<IGraph> graph, const int mode);
extern "C" SEXP _igraphlite_connected_components_(SEXP graph, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(connected_components_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(mode)));
  END_CPP11
}
// components.cpp
bool is_connected_(const cpp11::external_pointer<IGraph> graph, const int mode);
extern "C" SEXP _igraphlite_is_connected_(SEXP graph, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_connected_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(mode)));
  END_CPP11
}
// components.cpp
SEXP count_reachable_(const cpp11::external_pointer<IGraph> graph, const int mode);
extern "C" SEXP _igraphlite_count_reachable_(SEXP graph, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(count_reachable_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(mode)));
  END_CPP11
}
// components.cpp
SEXP transitive_closure_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_transitive_closure_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(transitive_closure_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// components.cpp
SEXP articulation_points_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_articulation_points_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(articulation_points_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// components.cpp
SEXP bridges_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_bridges_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(bridges_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// components.cpp
bool is_biconnected_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_is_biconnected_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_biconnected_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// cycles.cpp
SEXP topological_sorting_(const cpp11::external_pointer<IGraph> graph, const int mode);
extern "C" SEXP _igraphlite_topological_sorting_(SEXP graph, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(topological_sorting_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(mode)));
  END_CPP11
}
// cycles.cpp
bool is_dag_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_is_dag_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_dag_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// cycles.cpp
SEXP is_eulerian_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_is_eulerian_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_eulerian_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// data.cpp
SEXP as_adjlist_(const cpp11::external_pointer<IGraph> graph, const int mode, const int loops, const bool multiple);
extern "C" SEXP _igraphlite_as_adjlist_(SEXP graph, SEXP mode, SEXP loops, SEXP multiple) {
  BEGIN_CPP11
    return cpp11::as_sexp(as_adjlist_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<const int>>(loops), cpp11::as_cpp<cpp11::decay_t<const bool>>(multiple)));
  END_CPP11
}
// data.cpp
SEXP as_inclist_(const cpp11::external_pointer<IGraph> graph, const int mode, const int loops);
extern "C" SEXP _igraphlite_as_inclist_(SEXP graph, SEXP mode, SEXP loops) {
  BEGIN_CPP11
    return cpp11::as_sexp(as_inclist_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<const int>>(loops)));
  END_CPP11
}
// data.cpp
SEXP as_edgelist_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_as_edgelist_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(as_edgelist_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// data.cpp
SEXP as_data_frame_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_as_data_frame_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(as_data_frame_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// foreign.cpp
SEXP read_graph_edgelist_(const char* path, const bool directed);
extern "C" SEXP _igraphlite_read_graph_edgelist_(SEXP path, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_graph_edgelist_(cpp11::as_cpp<cpp11::decay_t<const char*>>(path), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed)));
  END_CPP11
}
// foreign.cpp
SEXP write_graph_edgelist_(const cpp11::external_pointer<IGraph> graph, const char* path);
extern "C" SEXP _igraphlite_write_graph_edgelist_(SEXP graph, SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(write_graph_edgelist_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const char*>>(path)));
  END_CPP11
}
// foreign.cpp
SEXP read_graph_ncol_(const char* path, const bool names, const bool directed);
extern "C" SEXP _igraphlite_read_graph_ncol_(SEXP path, SEXP names, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_graph_ncol_(cpp11::as_cpp<cpp11::decay_t<const char*>>(path), cpp11::as_cpp<cpp11::decay_t<const bool>>(names), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed)));
  END_CPP11
}
// foreign.cpp
SEXP write_graph_ncol_(const cpp11::external_pointer<IGraph> graph, const char* path);
extern "C" SEXP _igraphlite_write_graph_ncol_(SEXP graph, SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(write_graph_ncol_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const char*>>(path)));
  END_CPP11
}
// foreign.cpp
SEXP read_graph_lgl_(const char* path, const bool names, const bool directed);
extern "C" SEXP _igraphlite_read_graph_lgl_(SEXP path, SEXP names, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_graph_lgl_(cpp11::as_cpp<cpp11::decay_t<const char*>>(path), cpp11::as_cpp<cpp11::decay_t<const bool>>(names), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed)));
  END_CPP11
}
// foreign.cpp
SEXP write_graph_lgl_(const cpp11::external_pointer<IGraph> graph, const char* path, const bool isolates);
extern "C" SEXP _igraphlite_write_graph_lgl_(SEXP graph, SEXP path, SEXP isolates) {
  BEGIN_CPP11
    return cpp11::as_sexp(write_graph_lgl_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const char*>>(path), cpp11::as_cpp<cpp11::decay_t<const bool>>(isolates)));
  END_CPP11
}
// foreign.cpp
SEXP read_graph_graphml_(const char* path, const int index);
extern "C" SEXP _igraphlite_read_graph_graphml_(SEXP path, SEXP index) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_graph_graphml_(cpp11::as_cpp<cpp11::decay_t<const char*>>(path), cpp11::as_cpp<cpp11::decay_t<const int>>(index)));
  END_CPP11
}
// foreign.cpp
SEXP write_graph_graphml_(const cpp11::external_pointer<IGraph> graph, const char* path, const bool prefixattr);
extern "C" SEXP _igraphlite_write_graph_graphml_(SEXP graph, SEXP path, SEXP prefixattr) {
  BEGIN_CPP11
    return cpp11::as_sexp(write_graph_graphml_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const char*>>(path), cpp11::as_cpp<cpp11::decay_t<const bool>>(prefixattr)));
  END_CPP11
}
// foreign.cpp
SEXP read_graph_gml_(const char* path);
extern "C" SEXP _igraphlite_read_graph_gml_(SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_graph_gml_(cpp11::as_cpp<cpp11::decay_t<const char*>>(path)));
  END_CPP11
}
// foreign.cpp
SEXP write_graph_gml_(const cpp11::external_pointer<IGraph> graph, const char* path, const char* creator);
extern "C" SEXP _igraphlite_write_graph_gml_(SEXP graph, SEXP path, SEXP creator) {
  BEGIN_CPP11
    return cpp11::as_sexp(write_graph_gml_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const char*>>(path), cpp11::as_cpp<cpp11::decay_t<const char*>>(creator)));
  END_CPP11
}
// foreign.cpp
SEXP read_graph_pajek_(const char* path);
extern "C" SEXP _igraphlite_read_graph_pajek_(SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_graph_pajek_(cpp11::as_cpp<cpp11::decay_t<const char*>>(path)));
  END_CPP11
}
// foreign.cpp
SEXP write_graph_pajek_(const cpp11::external_pointer<IGraph> graph, const char* path);
extern "C" SEXP _igraphlite_write_graph_pajek_(SEXP graph, SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(write_graph_pajek_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const char*>>(path)));
  END_CPP11
}
// foreign.cpp
SEXP read_graph_dl_(const char* path, const bool directed);
extern "C" SEXP _igraphlite_read_graph_dl_(SEXP path, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_graph_dl_(cpp11::as_cpp<cpp11::decay_t<const char*>>(path), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed)));
  END_CPP11
}
// foreign.cpp
SEXP write_graph_dot_(const cpp11::external_pointer<IGraph> graph, const char* path);
extern "C" SEXP _igraphlite_write_graph_dot_(SEXP graph, SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(write_graph_dot_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const char*>>(path)));
  END_CPP11
}
// foreign.cpp
SEXP write_graph_leda_(const cpp11::external_pointer<IGraph> graph, const char* path);
extern "C" SEXP _igraphlite_write_graph_leda_(SEXP graph, SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(write_graph_leda_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const char*>>(path)));
  END_CPP11
}
// games.cpp
SEXP erdos_renyi_game_gnm_(const int n, const int m, const bool directed, const int edge_type_sw);
extern "C" SEXP _igraphlite_erdos_renyi_game_gnm_(SEXP n, SEXP m, SEXP directed, SEXP edge_type_sw) {
  BEGIN_CPP11
    return cpp11::as_sexp(erdos_renyi_game_gnm_(cpp11::as_cpp<cpp11::decay_t<const int>>(n), cpp11::as_cpp<cpp11::decay_t<const int>>(m), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const int>>(edge_type_sw)));
  END_CPP11
}
// games.cpp
SEXP erdos_renyi_game_gnp_(const int n, const double p_, const bool directed, const int edge_type_sw);
extern "C" SEXP _igraphlite_erdos_renyi_game_gnp_(SEXP n, SEXP p_, SEXP directed, SEXP edge_type_sw) {
  BEGIN_CPP11
    return cpp11::as_sexp(erdos_renyi_game_gnp_(cpp11::as_cpp<cpp11::decay_t<const int>>(n), cpp11::as_cpp<cpp11::decay_t<const double>>(p_), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const int>>(edge_type_sw)));
  END_CPP11
}
// games.cpp
SEXP degree_sequence_game_(const cpp11::integers& out_degrees, const cpp11::integers& in_degrees, const int method);
extern "C" SEXP _igraphlite_degree_sequence_game_(SEXP out_degrees, SEXP in_degrees, SEXP method) {
  BEGIN_CPP11
    return cpp11::as_sexp(degree_sequence_game_(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(out_degrees), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(in_degrees), cpp11::as_cpp<cpp11::decay_t<const int>>(method)));
  END_CPP11
}
// games.cpp
SEXP k_regular_game_(const int n, const int k, const bool directed, const bool multiple);
extern "C" SEXP _igraphlite_k_regular_game_(SEXP n, SEXP k, SEXP directed, SEXP multiple) {
  BEGIN_CPP11
    return cpp11::as_sexp(k_regular_game_(cpp11::as_cpp<cpp11::decay_t<const int>>(n), cpp11::as_cpp<cpp11::decay_t<const int>>(k), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const bool>>(multiple)));
  END_CPP11
}
// games.cpp
SEXP watts_strogatz_game_(const int dim, const int size, const int nei, const double prob, const int edge_type_sw);
extern "C" SEXP _igraphlite_watts_strogatz_game_(SEXP dim, SEXP size, SEXP nei, SEXP prob, SEXP edge_type_sw) {
  BEGIN_CPP11
    return cpp11::as_sexp(watts_strogatz_game_(cpp11::as_cpp<cpp11::decay_t<const int>>(dim), cpp11::as_cpp<cpp11::decay_t<const int>>(size), cpp11::as_cpp<cpp11::decay_t<const int>>(nei), cpp11::as_cpp<cpp11::decay_t<const double>>(prob), cpp11::as_cpp<cpp11::decay_t<const int>>(edge_type_sw)));
  END_CPP11
}
// games.cpp
void rewire_edges_(const cpp11::external_pointer<IGraph> graph, const double prob, const int edge_type_sw);
extern "C" SEXP _igraphlite_rewire_edges_(SEXP graph, SEXP prob, SEXP edge_type_sw) {
  BEGIN_CPP11
    rewire_edges_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const double>>(prob), cpp11::as_cpp<cpp11::decay_t<const int>>(edge_type_sw));
    return R_NilValue;
  END_CPP11
}
// generators.cpp
SEXP graph_create_(const cpp11::integers& edges, int n, bool directed);
extern "C" SEXP _igraphlite_graph_create_(SEXP edges, SEXP n, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_create_(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(edges), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}
// generators.cpp
SEXP graph_star_(int n, int mode, int center);
extern "C" SEXP _igraphlite_graph_star_(SEXP n, SEXP mode, SEXP center) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_star_(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(mode), cpp11::as_cpp<cpp11::decay_t<int>>(center)));
  END_CPP11
}
// generators.cpp
SEXP graph_hypercube_(int n, const bool directed);
extern "C" SEXP _igraphlite_graph_hypercube_(SEXP n, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_hypercube_(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed)));
  END_CPP11
}
// generators.cpp
SEXP graph_square_lattice_(const cpp11::integers& dim, int nei, bool directed, bool mutual, bool circular);
extern "C" SEXP _igraphlite_graph_square_lattice_(SEXP dim, SEXP nei, SEXP directed, SEXP mutual, SEXP circular) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_square_lattice_(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(dim), cpp11::as_cpp<cpp11::decay_t<int>>(nei), cpp11::as_cpp<cpp11::decay_t<bool>>(directed), cpp11::as_cpp<cpp11::decay_t<bool>>(mutual), cpp11::as_cpp<cpp11::decay_t<bool>>(circular)));
  END_CPP11
}
// generators.cpp
SEXP graph_triangular_lattice_(const cpp11::integers& dims, const bool directed, const bool mutual);
extern "C" SEXP _igraphlite_graph_triangular_lattice_(SEXP dims, SEXP directed, SEXP mutual) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_triangular_lattice_(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(dims), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const bool>>(mutual)));
  END_CPP11
}
// generators.cpp
SEXP graph_hexagonal_lattice_(const cpp11::integers& dims, const bool directed, const bool mutual);
extern "C" SEXP _igraphlite_graph_hexagonal_lattice_(SEXP dims, SEXP directed, SEXP mutual) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_hexagonal_lattice_(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(dims), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const bool>>(mutual)));
  END_CPP11
}
// generators.cpp
SEXP graph_ring_(int n, bool directed, bool mutual, bool circular);
extern "C" SEXP _igraphlite_graph_ring_(SEXP n, SEXP directed, SEXP mutual, SEXP circular) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_ring_(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<bool>>(directed), cpp11::as_cpp<cpp11::decay_t<bool>>(mutual), cpp11::as_cpp<cpp11::decay_t<bool>>(circular)));
  END_CPP11
}
// generators.cpp
SEXP graph_lcf_(const int n, const cpp11::integers& shifts, const int repeats);
extern "C" SEXP _igraphlite_graph_lcf_(SEXP n, SEXP shifts, SEXP repeats) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_lcf_(cpp11::as_cpp<cpp11::decay_t<const int>>(n), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(shifts), cpp11::as_cpp<cpp11::decay_t<const int>>(repeats)));
  END_CPP11
}
// generators.cpp
SEXP graph_circulant_(int n, const cpp11::integers& shifts, bool directed);
extern "C" SEXP _igraphlite_graph_circulant_(SEXP n, SEXP shifts, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_circulant_(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(shifts), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}
// generators.cpp
SEXP graph_kary_tree_(int n, int children, int mode);
extern "C" SEXP _igraphlite_graph_kary_tree_(SEXP n, SEXP children, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_kary_tree_(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(children), cpp11::as_cpp<cpp11::decay_t<int>>(mode)));
  END_CPP11
}
// generators.cpp
SEXP graph_full_(int n, bool directed, bool loops);
extern "C" SEXP _igraphlite_graph_full_(SEXP n, SEXP directed, SEXP loops) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_full_(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<bool>>(directed), cpp11::as_cpp<cpp11::decay_t<bool>>(loops)));
  END_CPP11
}
// generators.cpp
SEXP graph_famous_(const char* name);
extern "C" SEXP _igraphlite_graph_famous_(SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_famous_(cpp11::as_cpp<cpp11::decay_t<const char*>>(name)));
  END_CPP11
}
// generators.cpp
SEXP graph_from_edgelist_(const cpp11::sexp edgelist, bool directed);
extern "C" SEXP _igraphlite_graph_from_edgelist_(SEXP edgelist, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_from_edgelist_(cpp11::as_cpp<cpp11::decay_t<const cpp11::sexp>>(edgelist), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}
// generators.cpp
SEXP graph_from_data_frame_(const cpp11::data_frame& df, bool directed);
extern "C" SEXP _igraphlite_graph_from_data_frame_(SEXP df, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_from_data_frame_(cpp11::as_cpp<cpp11::decay_t<const cpp11::data_frame&>>(df), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}
// generators.cpp
SEXP graph_from_symbolic_edgelist_(const cpp11::sexp edgelist, bool directed);
extern "C" SEXP _igraphlite_graph_from_symbolic_edgelist_(SEXP edgelist, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_from_symbolic_edgelist_(cpp11::as_cpp<cpp11::decay_t<const cpp11::sexp>>(edgelist), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}
// generators.cpp
SEXP graph_from_symbolic_edges_(const cpp11::sexp edges, bool directed);
extern "C" SEXP _igraphlite_graph_from_symbolic_edges_(SEXP edges, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_from_symbolic_edges_(cpp11::as_cpp<cpp11::decay_t<const cpp11::sexp>>(edges), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}
// init.cpp
cpp11::r_string igraph_version_();
extern "C" SEXP _igraphlite_igraph_version_() {
  BEGIN_CPP11
    return cpp11::as_sexp(igraph_version_());
  END_CPP11
}
// init.cpp
void rng_seed(long seed);
extern "C" SEXP _igraphlite_rng_seed(SEXP seed) {
  BEGIN_CPP11
    rng_seed(cpp11::as_cpp<cpp11::decay_t<long>>(seed));
    return R_NilValue;
  END_CPP11
}
// isomorphism.cpp
bool isomorphic_(const cpp11::external_pointer<IGraph>& graph1, const cpp11::external_pointer<IGraph>& graph2);
extern "C" SEXP _igraphlite_isomorphic_(SEXP graph1, SEXP graph2) {
  BEGIN_CPP11
    return cpp11::as_sexp(isomorphic_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>&>>(graph1), cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>&>>(graph2)));
  END_CPP11
}
// isomorphism.cpp
bool subisomorphic_(const cpp11::external_pointer<IGraph>& graph1, const cpp11::external_pointer<IGraph>& graph2);
extern "C" SEXP _igraphlite_subisomorphic_(SEXP graph1, SEXP graph2) {
  BEGIN_CPP11
    return cpp11::as_sexp(subisomorphic_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>&>>(graph1), cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>&>>(graph2)));
  END_CPP11
}
// isomorphism.cpp
SEXP canonical_permutation_(const cpp11::external_pointer<IGraph>& graph, const cpp11::integers& colors);
extern "C" SEXP _igraphlite_canonical_permutation_(SEXP graph, SEXP colors) {
  BEGIN_CPP11
    return cpp11::as_sexp(canonical_permutation_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>&>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(colors)));
  END_CPP11
}
// layout.cpp
void layout_random_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_layout_random_(SEXP graph) {
  BEGIN_CPP11
    layout_random_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph));
    return R_NilValue;
  END_CPP11
}
// layout.cpp
void layout_circle_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& order);
extern "C" SEXP _igraphlite_layout_circle_(SEXP graph, SEXP order) {
  BEGIN_CPP11
    layout_circle_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(order));
    return R_NilValue;
  END_CPP11
}
// layout.cpp
void layout_star_(const cpp11::external_pointer<IGraph> graph, int center, const cpp11::integers& order);
extern "C" SEXP _igraphlite_layout_star_(SEXP graph, SEXP center, SEXP order) {
  BEGIN_CPP11
    layout_star_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<int>>(center), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(order));
    return R_NilValue;
  END_CPP11
}
// layout.cpp
void layout_grid_(const cpp11::external_pointer<IGraph> graph, const int width);
extern "C" SEXP _igraphlite_layout_grid_(SEXP graph, SEXP width) {
  BEGIN_CPP11
    layout_grid_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(width));
    return R_NilValue;
  END_CPP11
}
// layout.cpp
void layout_drl_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_layout_drl_(SEXP graph) {
  BEGIN_CPP11
    layout_drl_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph));
    return R_NilValue;
  END_CPP11
}
// layout.cpp
void layout_fruchterman_reingold_(const cpp11::external_pointer<IGraph> graph, int grid);
extern "C" SEXP _igraphlite_layout_fruchterman_reingold_(SEXP graph, SEXP grid) {
  BEGIN_CPP11
    layout_fruchterman_reingold_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<int>>(grid));
    return R_NilValue;
  END_CPP11
}
// layout.cpp
void layout_mds_(const cpp11::external_pointer<IGraph> graph, SEXP dist);
extern "C" SEXP _igraphlite_layout_mds_(SEXP graph, SEXP dist) {
  BEGIN_CPP11
    layout_mds_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<SEXP>>(dist));
    return R_NilValue;
  END_CPP11
}
// layout.cpp
void layout_reingold_tilford_(const cpp11::external_pointer<IGraph> graph, int mode, const cpp11::integers& roots);
extern "C" SEXP _igraphlite_layout_reingold_tilford_(SEXP graph, SEXP mode, SEXP roots) {
  BEGIN_CPP11
    layout_reingold_tilford_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<int>>(mode), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(roots));
    return R_NilValue;
  END_CPP11
}
// layout.cpp
void layout_reingold_tilford_circular_(const cpp11::external_pointer<IGraph> graph, int mode, const cpp11::integers& roots);
extern "C" SEXP _igraphlite_layout_reingold_tilford_circular_(SEXP graph, SEXP mode, SEXP roots) {
  BEGIN_CPP11
    layout_reingold_tilford_circular_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<int>>(mode), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(roots));
    return R_NilValue;
  END_CPP11
}
// neighborhood.cpp
SEXP neighborhood_size_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids, const int order, const int mode, const int mindist);
extern "C" SEXP _igraphlite_neighborhood_size_(SEXP graph, SEXP vids, SEXP order, SEXP mode, SEXP mindist) {
  BEGIN_CPP11
    return cpp11::as_sexp(neighborhood_size_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const int>>(order), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<const int>>(mindist)));
  END_CPP11
}
// neighborhood.cpp
SEXP neighborhood_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids, const int order, const int mode, const int mindist);
extern "C" SEXP _igraphlite_neighborhood_(SEXP graph, SEXP vids, SEXP order, SEXP mode, SEXP mindist) {
  BEGIN_CPP11
    return cpp11::as_sexp(neighborhood_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const int>>(order), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<const int>>(mindist)));
  END_CPP11
}
// operators.cpp
void rewire_(const cpp11::external_pointer<IGraph> graph, const int n, const int edge_type_sw);
extern "C" SEXP _igraphlite_rewire_(SEXP graph, SEXP n, SEXP edge_type_sw) {
  BEGIN_CPP11
    rewire_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(n), cpp11::as_cpp<cpp11::decay_t<const int>>(edge_type_sw));
    return R_NilValue;
  END_CPP11
}
// operators.cpp
SEXP induced_subgraph_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids, int impl);
extern "C" SEXP _igraphlite_induced_subgraph_(SEXP graph, SEXP vids, SEXP impl) {
  BEGIN_CPP11
    return cpp11::as_sexp(induced_subgraph_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<int>>(impl)));
  END_CPP11
}
// operators.cpp
SEXP induced_subgraph_edges_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids);
extern "C" SEXP _igraphlite_induced_subgraph_edges_(SEXP graph, SEXP vids) {
  BEGIN_CPP11
    return cpp11::as_sexp(induced_subgraph_edges_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids)));
  END_CPP11
}
// operators.cpp
SEXP subgraph_from_edges_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& eids, const bool delete_vertices);
extern "C" SEXP _igraphlite_subgraph_from_edges_(SEXP graph, SEXP eids, SEXP delete_vertices) {
  BEGIN_CPP11
    return cpp11::as_sexp(subgraph_from_edges_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(eids), cpp11::as_cpp<cpp11::decay_t<const bool>>(delete_vertices)));
  END_CPP11
}
// operators.cpp
SEXP permute_vertices_(const cpp11::external_pointer<IGraph>& graph, const cpp11::integers& perm);
extern "C" SEXP _igraphlite_permute_vertices_(SEXP graph, SEXP perm) {
  BEGIN_CPP11
    return cpp11::as_sexp(permute_vertices_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>&>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(perm)));
  END_CPP11
}
// paths.cpp
SEXP distances_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, const cpp11::integers& from, const cpp11::integers& to, const int mode, const double cutoff);
extern "C" SEXP _igraphlite_distances_(SEXP graph, SEXP weights, SEXP from, SEXP to, SEXP mode, SEXP cutoff) {
  BEGIN_CPP11
    return cpp11::as_sexp(distances_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(from), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(to), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<const double>>(cutoff)));
  END_CPP11
}
// paths.cpp
SEXP get_shortest_paths_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, int from, const cpp11::integers& to, int mode);
extern "C" SEXP _igraphlite_get_shortest_paths_(SEXP graph, SEXP weights, SEXP from, SEXP to, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_shortest_paths_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<int>>(from), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(to), cpp11::as_cpp<cpp11::decay_t<int>>(mode)));
  END_CPP11
}
// paths.cpp
SEXP get_all_shortest_paths_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, int from, const cpp11::integers& to, int mode);
extern "C" SEXP _igraphlite_get_all_shortest_paths_(SEXP graph, SEXP weights, SEXP from, SEXP to, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_all_shortest_paths_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<int>>(from), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(to), cpp11::as_cpp<cpp11::decay_t<int>>(mode)));
  END_CPP11
}
// paths.cpp
SEXP get_all_simple_paths_(const cpp11::external_pointer<IGraph> graph, int from, const cpp11::integers& to, int mode, const int minlen, const int maxlen, const int max_results);
extern "C" SEXP _igraphlite_get_all_simple_paths_(SEXP graph, SEXP from, SEXP to, SEXP mode, SEXP minlen, SEXP maxlen, SEXP max_results) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_all_simple_paths_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<int>>(from), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(to), cpp11::as_cpp<cpp11::decay_t<int>>(mode), cpp11::as_cpp<cpp11::decay_t<const int>>(minlen), cpp11::as_cpp<cpp11::decay_t<const int>>(maxlen), cpp11::as_cpp<cpp11::decay_t<const int>>(max_results)));
  END_CPP11
}
// paths.cpp
double average_path_length_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, bool directed, bool unconn);
extern "C" SEXP _igraphlite_average_path_length_(SEXP graph, SEXP weights, SEXP directed, SEXP unconn) {
  BEGIN_CPP11
    return cpp11::as_sexp(average_path_length_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<bool>>(directed), cpp11::as_cpp<cpp11::decay_t<bool>>(unconn)));
  END_CPP11
}
// paths.cpp
SEXP path_length_hist_(const cpp11::external_pointer<IGraph> graph, bool directed);
extern "C" SEXP _igraphlite_path_length_hist_(SEXP graph, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(path_length_hist_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}
// paths.cpp
SEXP eccentricity_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, const cpp11::integers& vids, const int mode);
extern "C" SEXP _igraphlite_eccentricity_(SEXP graph, SEXP weights, SEXP vids, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(eccentricity_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const int>>(mode)));
  END_CPP11
}
// paths.cpp
double diameter_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, bool directed, bool unconn);
extern "C" SEXP _igraphlite_diameter_(SEXP graph, SEXP weights, SEXP directed, SEXP unconn) {
  BEGIN_CPP11
    return cpp11::as_sexp(diameter_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<bool>>(directed), cpp11::as_cpp<cpp11::decay_t<bool>>(unconn)));
  END_CPP11
}
// paths.cpp
double radius_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, const int mode);
extern "C" SEXP _igraphlite_radius_(SEXP graph, SEXP weights, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(radius_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const int>>(mode)));
  END_CPP11
}
// paths.cpp
double global_efficiency_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, const bool directed);
extern "C" SEXP _igraphlite_global_efficiency_(SEXP graph, SEXP weights, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(global_efficiency_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed)));
  END_CPP11
}
// paths.cpp
SEXP local_efficiency_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, const cpp11::integers& vids, const bool directed, const int mode);
extern "C" SEXP _igraphlite_local_efficiency_(SEXP graph, SEXP weights, SEXP vids, SEXP directed, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(local_efficiency_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const int>>(mode)));
  END_CPP11
}
// paths.cpp
double average_local_efficiency_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, const bool directed, const int mode);
extern "C" SEXP _igraphlite_average_local_efficiency_(SEXP graph, SEXP weights, SEXP directed, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(average_local_efficiency_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed), cpp11::as_cpp<cpp11::decay_t<const int>>(mode)));
  END_CPP11
}
// paths.cpp
SEXP expand_path_to_pairs_(const cpp11::integers& path);
extern "C" SEXP _igraphlite_expand_path_to_pairs_(SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(expand_path_to_pairs_(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(path)));
  END_CPP11
}
// paths.cpp
double mean_distances_cpp_(const cpp11::external_pointer<IGraph> graph, const cpp11::doubles& weights, const cpp11::integers& from, const cpp11::integers& to, int mode);
extern "C" SEXP _igraphlite_mean_distances_cpp_(SEXP graph, SEXP weights, SEXP from, SEXP to, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(mean_distances_cpp_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(from), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(to), cpp11::as_cpp<cpp11::decay_t<int>>(mode)));
  END_CPP11
}
// paths.cpp
SEXP path_length_count_within(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids);
extern "C" SEXP _igraphlite_path_length_count_within(SEXP graph, SEXP vids) {
  BEGIN_CPP11
    return cpp11::as_sexp(path_length_count_within(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids)));
  END_CPP11
}
// paths.cpp
SEXP path_length_count_between(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& from, const cpp11::integers& to);
extern "C" SEXP _igraphlite_path_length_count_between(SEXP graph, SEXP from, SEXP to) {
  BEGIN_CPP11
    return cpp11::as_sexp(path_length_count_between(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(from), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(to)));
  END_CPP11
}
// structural.cpp
bool are_adjacent_(const cpp11::external_pointer<IGraph> graph, int v1, int v2);
extern "C" SEXP _igraphlite_are_adjacent_(SEXP graph, SEXP v1, SEXP v2) {
  BEGIN_CPP11
    return cpp11::as_sexp(are_adjacent_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<int>>(v1), cpp11::as_cpp<cpp11::decay_t<int>>(v2)));
  END_CPP11
}
// structural.cpp
bool is_simple_(const cpp11::external_pointer<IGraph> graph, const bool directed);
extern "C" SEXP _igraphlite_is_simple_(SEXP graph, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_simple_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed)));
  END_CPP11
}
// structural.cpp
bool is_acyclic_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_is_acyclic_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_acyclic_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// structural.cpp
bool has_loop_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_has_loop_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(has_loop_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// structural.cpp
int count_loops_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_count_loops_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(count_loops_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// structural.cpp
bool has_multiple_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_has_multiple_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(has_multiple_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// structural.cpp
SEXP count_multiple_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& eids);
extern "C" SEXP _igraphlite_count_multiple_(SEXP graph, SEXP eids) {
  BEGIN_CPP11
    return cpp11::as_sexp(count_multiple_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(eids)));
  END_CPP11
}
// structural.cpp
double girth_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_girth_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(girth_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// structural.cpp
int maxdegree_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids, const int mode, const int loops);
extern "C" SEXP _igraphlite_maxdegree_(SEXP graph, SEXP vids, SEXP mode, SEXP loops) {
  BEGIN_CPP11
    return cpp11::as_sexp(maxdegree_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<const int>>(loops)));
  END_CPP11
}
// structural.cpp
SEXP strength_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids, const int mode, const int loops, const cpp11::doubles& weights);
extern "C" SEXP _igraphlite_strength_(SEXP graph, SEXP vids, SEXP mode, SEXP loops, SEXP weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(strength_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const int>>(mode), cpp11::as_cpp<cpp11::decay_t<const int>>(loops), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(weights)));
  END_CPP11
}
// structural.cpp
bool is_complete_(const cpp11::external_pointer<IGraph> graph);
extern "C" SEXP _igraphlite_is_complete_(SEXP graph) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_complete_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph)));
  END_CPP11
}
// structural.cpp
bool is_clique_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& candidate, const bool directed);
extern "C" SEXP _igraphlite_is_clique_(SEXP graph, SEXP candidate, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_clique_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(candidate), cpp11::as_cpp<cpp11::decay_t<const bool>>(directed)));
  END_CPP11
}
// structural.cpp
bool is_independent_vertex_set_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& candidate);
extern "C" SEXP _igraphlite_is_independent_vertex_set_(SEXP graph, SEXP candidate) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_independent_vertex_set_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(candidate)));
  END_CPP11
}
// structural.cpp
SEXP subcomponent_(const cpp11::external_pointer<IGraph> graph, const int v, const int mode);
extern "C" SEXP _igraphlite_subcomponent_(SEXP graph, SEXP v, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(subcomponent_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const int>>(v), cpp11::as_cpp<cpp11::decay_t<const int>>(mode)));
  END_CPP11
}
// structural.cpp
SEXP subcomponents_(const cpp11::external_pointer<IGraph> graph, const cpp11::integers& vids, const int mode);
extern "C" SEXP _igraphlite_subcomponents_(SEXP graph, SEXP vids, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(subcomponents_(cpp11::as_cpp<cpp11::decay_t<const cpp11::external_pointer<IGraph>>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(vids), cpp11::as_cpp<cpp11::decay_t<const int>>(mode)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_igraphlite_ECOUNT_MAX",                        (DL_FUNC) &_igraphlite_ECOUNT_MAX,                        0},
    {"_igraphlite_E_",                                (DL_FUNC) &_igraphlite_E_,                                1},
    {"_igraphlite_UNLIMITED",                         (DL_FUNC) &_igraphlite_UNLIMITED,                         0},
    {"_igraphlite_VCOUNT_MAX",                        (DL_FUNC) &_igraphlite_VCOUNT_MAX,                        0},
    {"_igraphlite_V_",                                (DL_FUNC) &_igraphlite_V_,                                1},
    {"_igraphlite_Vnames_",                           (DL_FUNC) &_igraphlite_Vnames_,                           1},
    {"_igraphlite_add_edges_",                        (DL_FUNC) &_igraphlite_add_edges_,                        2},
    {"_igraphlite_add_vertices_",                     (DL_FUNC) &_igraphlite_add_vertices_,                     2},
    {"_igraphlite_are_adjacent_",                     (DL_FUNC) &_igraphlite_are_adjacent_,                     3},
    {"_igraphlite_articulation_points_",              (DL_FUNC) &_igraphlite_articulation_points_,              1},
    {"_igraphlite_as_adjlist_",                       (DL_FUNC) &_igraphlite_as_adjlist_,                       4},
    {"_igraphlite_as_data_frame_",                    (DL_FUNC) &_igraphlite_as_data_frame_,                    1},
    {"_igraphlite_as_edgelist_",                      (DL_FUNC) &_igraphlite_as_edgelist_,                      1},
    {"_igraphlite_as_inclist_",                       (DL_FUNC) &_igraphlite_as_inclist_,                       3},
    {"_igraphlite_average_local_efficiency_",         (DL_FUNC) &_igraphlite_average_local_efficiency_,         4},
    {"_igraphlite_average_path_length_",              (DL_FUNC) &_igraphlite_average_path_length_,              4},
    {"_igraphlite_betweenness_",                      (DL_FUNC) &_igraphlite_betweenness_,                      6},
    {"_igraphlite_betweenness_subset_",               (DL_FUNC) &_igraphlite_betweenness_subset_,               7},
    {"_igraphlite_bridges_",                          (DL_FUNC) &_igraphlite_bridges_,                          1},
    {"_igraphlite_canonical_permutation_",            (DL_FUNC) &_igraphlite_canonical_permutation_,            2},
    {"_igraphlite_clique_number_",                    (DL_FUNC) &_igraphlite_clique_number_,                    1},
    {"_igraphlite_clique_size_hist_",                 (DL_FUNC) &_igraphlite_clique_size_hist_,                 3},
    {"_igraphlite_cliques_",                          (DL_FUNC) &_igraphlite_cliques_,                          4},
    {"_igraphlite_closeness_",                        (DL_FUNC) &_igraphlite_closeness_,                        5},
    {"_igraphlite_connected_components_",             (DL_FUNC) &_igraphlite_connected_components_,             2},
    {"_igraphlite_constraint_",                       (DL_FUNC) &_igraphlite_constraint_,                       3},
    {"_igraphlite_convergence_degree_",               (DL_FUNC) &_igraphlite_convergence_degree_,               1},
    {"_igraphlite_count_loops_",                      (DL_FUNC) &_igraphlite_count_loops_,                      1},
    {"_igraphlite_count_multiple_",                   (DL_FUNC) &_igraphlite_count_multiple_,                   2},
    {"_igraphlite_count_reachable_",                  (DL_FUNC) &_igraphlite_count_reachable_,                  2},
    {"_igraphlite_degree_",                           (DL_FUNC) &_igraphlite_degree_,                           4},
    {"_igraphlite_degree_sequence_game_",             (DL_FUNC) &_igraphlite_degree_sequence_game_,             3},
    {"_igraphlite_delete_edges_",                     (DL_FUNC) &_igraphlite_delete_edges_,                     2},
    {"_igraphlite_delete_vertices_",                  (DL_FUNC) &_igraphlite_delete_vertices_,                  2},
    {"_igraphlite_diameter_",                         (DL_FUNC) &_igraphlite_diameter_,                         4},
    {"_igraphlite_distances_",                        (DL_FUNC) &_igraphlite_distances_,                        6},
    {"_igraphlite_eccentricity_",                     (DL_FUNC) &_igraphlite_eccentricity_,                     4},
    {"_igraphlite_ecount_",                           (DL_FUNC) &_igraphlite_ecount_,                           1},
    {"_igraphlite_edge_",                             (DL_FUNC) &_igraphlite_edge_,                             2},
    {"_igraphlite_edge_betweenness_",                 (DL_FUNC) &_igraphlite_edge_betweenness_,                 6},
    {"_igraphlite_edge_betweenness_subset_",          (DL_FUNC) &_igraphlite_edge_betweenness_subset_,          7},
    {"_igraphlite_edges_",                            (DL_FUNC) &_igraphlite_edges_,                            3},
    {"_igraphlite_eigenvector_centrality_",           (DL_FUNC) &_igraphlite_eigenvector_centrality_,           3},
    {"_igraphlite_erdos_renyi_game_gnm_",             (DL_FUNC) &_igraphlite_erdos_renyi_game_gnm_,             4},
    {"_igraphlite_erdos_renyi_game_gnp_",             (DL_FUNC) &_igraphlite_erdos_renyi_game_gnp_,             4},
    {"_igraphlite_expand_path_to_pairs_",             (DL_FUNC) &_igraphlite_expand_path_to_pairs_,             1},
    {"_igraphlite_from_",                             (DL_FUNC) &_igraphlite_from_,                             1},
    {"_igraphlite_getEattr_",                         (DL_FUNC) &_igraphlite_getEattr_,                         1},
    {"_igraphlite_getVattr_",                         (DL_FUNC) &_igraphlite_getVattr_,                         1},
    {"_igraphlite_get_all_eids_between_",             (DL_FUNC) &_igraphlite_get_all_eids_between_,             4},
    {"_igraphlite_get_all_shortest_paths_",           (DL_FUNC) &_igraphlite_get_all_shortest_paths_,           5},
    {"_igraphlite_get_all_simple_paths_",             (DL_FUNC) &_igraphlite_get_all_simple_paths_,             7},
    {"_igraphlite_get_eids_",                         (DL_FUNC) &_igraphlite_get_eids_,                         4},
    {"_igraphlite_get_shortest_paths_",               (DL_FUNC) &_igraphlite_get_shortest_paths_,               5},
    {"_igraphlite_girth_",                            (DL_FUNC) &_igraphlite_girth_,                            1},
    {"_igraphlite_global_efficiency_",                (DL_FUNC) &_igraphlite_global_efficiency_,                3},
    {"_igraphlite_graph_circulant_",                  (DL_FUNC) &_igraphlite_graph_circulant_,                  3},
    {"_igraphlite_graph_copy_",                       (DL_FUNC) &_igraphlite_graph_copy_,                       1},
    {"_igraphlite_graph_create_",                     (DL_FUNC) &_igraphlite_graph_create_,                     3},
    {"_igraphlite_graph_empty_",                      (DL_FUNC) &_igraphlite_graph_empty_,                      2},
    {"_igraphlite_graph_famous_",                     (DL_FUNC) &_igraphlite_graph_famous_,                     1},
    {"_igraphlite_graph_from_data_frame_",            (DL_FUNC) &_igraphlite_graph_from_data_frame_,            2},
    {"_igraphlite_graph_from_edgelist_",              (DL_FUNC) &_igraphlite_graph_from_edgelist_,              2},
    {"_igraphlite_graph_from_symbolic_edgelist_",     (DL_FUNC) &_igraphlite_graph_from_symbolic_edgelist_,     2},
    {"_igraphlite_graph_from_symbolic_edges_",        (DL_FUNC) &_igraphlite_graph_from_symbolic_edges_,        2},
    {"_igraphlite_graph_full_",                       (DL_FUNC) &_igraphlite_graph_full_,                       3},
    {"_igraphlite_graph_hexagonal_lattice_",          (DL_FUNC) &_igraphlite_graph_hexagonal_lattice_,          3},
    {"_igraphlite_graph_hypercube_",                  (DL_FUNC) &_igraphlite_graph_hypercube_,                  2},
    {"_igraphlite_graph_kary_tree_",                  (DL_FUNC) &_igraphlite_graph_kary_tree_,                  3},
    {"_igraphlite_graph_lcf_",                        (DL_FUNC) &_igraphlite_graph_lcf_,                        3},
    {"_igraphlite_graph_ring_",                       (DL_FUNC) &_igraphlite_graph_ring_,                       4},
    {"_igraphlite_graph_square_lattice_",             (DL_FUNC) &_igraphlite_graph_square_lattice_,             5},
    {"_igraphlite_graph_star_",                       (DL_FUNC) &_igraphlite_graph_star_,                       3},
    {"_igraphlite_graph_triangular_lattice_",         (DL_FUNC) &_igraphlite_graph_triangular_lattice_,         3},
    {"_igraphlite_harmonic_centrality_",              (DL_FUNC) &_igraphlite_harmonic_centrality_,              5},
    {"_igraphlite_has_loop_",                         (DL_FUNC) &_igraphlite_has_loop_,                         1},
    {"_igraphlite_has_multiple_",                     (DL_FUNC) &_igraphlite_has_multiple_,                     1},
    {"_igraphlite_hub_and_authority_scores_",         (DL_FUNC) &_igraphlite_hub_and_authority_scores_,         2},
    {"_igraphlite_igraph_version_",                   (DL_FUNC) &_igraphlite_igraph_version_,                   0},
    {"_igraphlite_incident_",                         (DL_FUNC) &_igraphlite_incident_,                         4},
    {"_igraphlite_independence_number_",              (DL_FUNC) &_igraphlite_independence_number_,              1},
    {"_igraphlite_independent_vertex_sets_",          (DL_FUNC) &_igraphlite_independent_vertex_sets_,          4},
    {"_igraphlite_induced_subgraph_",                 (DL_FUNC) &_igraphlite_induced_subgraph_,                 3},
    {"_igraphlite_induced_subgraph_edges_",           (DL_FUNC) &_igraphlite_induced_subgraph_edges_,           2},
    {"_igraphlite_is_acyclic_",                       (DL_FUNC) &_igraphlite_is_acyclic_,                       1},
    {"_igraphlite_is_biconnected_",                   (DL_FUNC) &_igraphlite_is_biconnected_,                   1},
    {"_igraphlite_is_clique_",                        (DL_FUNC) &_igraphlite_is_clique_,                        3},
    {"_igraphlite_is_complete_",                      (DL_FUNC) &_igraphlite_is_complete_,                      1},
    {"_igraphlite_is_connected_",                     (DL_FUNC) &_igraphlite_is_connected_,                     2},
    {"_igraphlite_is_dag_",                           (DL_FUNC) &_igraphlite_is_dag_,                           1},
    {"_igraphlite_is_directed_",                      (DL_FUNC) &_igraphlite_is_directed_,                      1},
    {"_igraphlite_is_eulerian_",                      (DL_FUNC) &_igraphlite_is_eulerian_,                      1},
    {"_igraphlite_is_independent_vertex_set_",        (DL_FUNC) &_igraphlite_is_independent_vertex_set_,        2},
    {"_igraphlite_is_same_graph_",                    (DL_FUNC) &_igraphlite_is_same_graph_,                    2},
    {"_igraphlite_is_simple_",                        (DL_FUNC) &_igraphlite_is_simple_,                        2},
    {"_igraphlite_isomorphic_",                       (DL_FUNC) &_igraphlite_isomorphic_,                       2},
    {"_igraphlite_k_regular_game_",                   (DL_FUNC) &_igraphlite_k_regular_game_,                   4},
    {"_igraphlite_largest_cliques_",                  (DL_FUNC) &_igraphlite_largest_cliques_,                  1},
    {"_igraphlite_largest_independent_vertex_sets_",  (DL_FUNC) &_igraphlite_largest_independent_vertex_sets_,  1},
    {"_igraphlite_layout_circle_",                    (DL_FUNC) &_igraphlite_layout_circle_,                    2},
    {"_igraphlite_layout_drl_",                       (DL_FUNC) &_igraphlite_layout_drl_,                       1},
    {"_igraphlite_layout_fruchterman_reingold_",      (DL_FUNC) &_igraphlite_layout_fruchterman_reingold_,      2},
    {"_igraphlite_layout_grid_",                      (DL_FUNC) &_igraphlite_layout_grid_,                      2},
    {"_igraphlite_layout_mds_",                       (DL_FUNC) &_igraphlite_layout_mds_,                       2},
    {"_igraphlite_layout_random_",                    (DL_FUNC) &_igraphlite_layout_random_,                    1},
    {"_igraphlite_layout_reingold_tilford_",          (DL_FUNC) &_igraphlite_layout_reingold_tilford_,          3},
    {"_igraphlite_layout_reingold_tilford_circular_", (DL_FUNC) &_igraphlite_layout_reingold_tilford_circular_, 3},
    {"_igraphlite_layout_star_",                      (DL_FUNC) &_igraphlite_layout_star_,                      3},
    {"_igraphlite_local_efficiency_",                 (DL_FUNC) &_igraphlite_local_efficiency_,                 5},
    {"_igraphlite_maxdegree_",                        (DL_FUNC) &_igraphlite_maxdegree_,                        4},
    {"_igraphlite_maximal_cliques_",                  (DL_FUNC) &_igraphlite_maximal_cliques_,                  4},
    {"_igraphlite_maximal_cliques_count_",            (DL_FUNC) &_igraphlite_maximal_cliques_count_,            3},
    {"_igraphlite_maximal_cliques_hist_",             (DL_FUNC) &_igraphlite_maximal_cliques_hist_,             3},
    {"_igraphlite_maximal_independent_vertex_sets_",  (DL_FUNC) &_igraphlite_maximal_independent_vertex_sets_,  4},
    {"_igraphlite_mean_distances_cpp_",               (DL_FUNC) &_igraphlite_mean_distances_cpp_,               5},
    {"_igraphlite_mutate_Eattr_",                     (DL_FUNC) &_igraphlite_mutate_Eattr_,                     3},
    {"_igraphlite_mutate_Vattr_",                     (DL_FUNC) &_igraphlite_mutate_Vattr_,                     3},
    {"_igraphlite_neighborhood_",                     (DL_FUNC) &_igraphlite_neighborhood_,                     5},
    {"_igraphlite_neighborhood_size_",                (DL_FUNC) &_igraphlite_neighborhood_size_,                5},
    {"_igraphlite_neighbors_",                        (DL_FUNC) &_igraphlite_neighbors_,                        5},
    {"_igraphlite_pagerank_",                         (DL_FUNC) &_igraphlite_pagerank_,                         6},
    {"_igraphlite_path_length_count_between",         (DL_FUNC) &_igraphlite_path_length_count_between,         3},
    {"_igraphlite_path_length_count_within",          (DL_FUNC) &_igraphlite_path_length_count_within,          2},
    {"_igraphlite_path_length_hist_",                 (DL_FUNC) &_igraphlite_path_length_hist_,                 2},
    {"_igraphlite_permute_vertices_",                 (DL_FUNC) &_igraphlite_permute_vertices_,                 2},
    {"_igraphlite_radius_",                           (DL_FUNC) &_igraphlite_radius_,                           3},
    {"_igraphlite_read_graph_dl_",                    (DL_FUNC) &_igraphlite_read_graph_dl_,                    2},
    {"_igraphlite_read_graph_edgelist_",              (DL_FUNC) &_igraphlite_read_graph_edgelist_,              2},
    {"_igraphlite_read_graph_gml_",                   (DL_FUNC) &_igraphlite_read_graph_gml_,                   1},
    {"_igraphlite_read_graph_graphml_",               (DL_FUNC) &_igraphlite_read_graph_graphml_,               2},
    {"_igraphlite_read_graph_lgl_",                   (DL_FUNC) &_igraphlite_read_graph_lgl_,                   3},
    {"_igraphlite_read_graph_ncol_",                  (DL_FUNC) &_igraphlite_read_graph_ncol_,                  3},
    {"_igraphlite_read_graph_pajek_",                 (DL_FUNC) &_igraphlite_read_graph_pajek_,                 1},
    {"_igraphlite_rewire_",                           (DL_FUNC) &_igraphlite_rewire_,                           3},
    {"_igraphlite_rewire_edges_",                     (DL_FUNC) &_igraphlite_rewire_edges_,                     3},
    {"_igraphlite_rng_seed",                          (DL_FUNC) &_igraphlite_rng_seed,                          1},
    {"_igraphlite_setEattr_",                         (DL_FUNC) &_igraphlite_setEattr_,                         2},
    {"_igraphlite_setVattr_",                         (DL_FUNC) &_igraphlite_setVattr_,                         2},
    {"_igraphlite_strength_",                         (DL_FUNC) &_igraphlite_strength_,                         5},
    {"_igraphlite_subcomponent_",                     (DL_FUNC) &_igraphlite_subcomponent_,                     3},
    {"_igraphlite_subcomponents_",                    (DL_FUNC) &_igraphlite_subcomponents_,                    3},
    {"_igraphlite_subgraph_from_edges_",              (DL_FUNC) &_igraphlite_subgraph_from_edges_,              3},
    {"_igraphlite_subisomorphic_",                    (DL_FUNC) &_igraphlite_subisomorphic_,                    2},
    {"_igraphlite_to_",                               (DL_FUNC) &_igraphlite_to_,                               1},
    {"_igraphlite_topological_sorting_",              (DL_FUNC) &_igraphlite_topological_sorting_,              2},
    {"_igraphlite_transitive_closure_",               (DL_FUNC) &_igraphlite_transitive_closure_,               1},
    {"_igraphlite_vcount_",                           (DL_FUNC) &_igraphlite_vcount_,                           1},
    {"_igraphlite_watts_strogatz_game_",              (DL_FUNC) &_igraphlite_watts_strogatz_game_,              5},
    {"_igraphlite_write_graph_dot_",                  (DL_FUNC) &_igraphlite_write_graph_dot_,                  2},
    {"_igraphlite_write_graph_edgelist_",             (DL_FUNC) &_igraphlite_write_graph_edgelist_,             2},
    {"_igraphlite_write_graph_gml_",                  (DL_FUNC) &_igraphlite_write_graph_gml_,                  3},
    {"_igraphlite_write_graph_graphml_",              (DL_FUNC) &_igraphlite_write_graph_graphml_,              3},
    {"_igraphlite_write_graph_leda_",                 (DL_FUNC) &_igraphlite_write_graph_leda_,                 2},
    {"_igraphlite_write_graph_lgl_",                  (DL_FUNC) &_igraphlite_write_graph_lgl_,                  3},
    {"_igraphlite_write_graph_ncol_",                 (DL_FUNC) &_igraphlite_write_graph_ncol_,                 2},
    {"_igraphlite_write_graph_pajek_",                (DL_FUNC) &_igraphlite_write_graph_pajek_,                2},
    {NULL, NULL, 0}
};
}

void igraphlite_init(DllInfo * dll);

extern "C" attribute_visible void R_init_igraphlite(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  igraphlite_init(dll);
  R_forceSymbols(dll, TRUE);
}
