// Generated by cpp11: do not edit by hand
// clang-format off

#include "igraphlite_types.h"
#include "cpp11/declarations.hpp"

// generators.cpp
IGraph graph_from_data_frame(const cpp11::data_frame& df, bool directed);
extern "C" SEXP _igraphlite_graph_from_data_frame(SEXP df, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_from_data_frame(cpp11::as_cpp<cpp11::decay_t<const cpp11::data_frame&>>(df), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}
// generators.cpp
IGraph graph_from_edgelist(const cpp11::doubles_matrix& edgelist, bool directed);
extern "C" SEXP _igraphlite_graph_from_edgelist(SEXP edgelist, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_from_edgelist(cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles_matrix&>>(edgelist), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}
// generators.cpp
IGraph graph_create(const cpp11::doubles& edges, int n, bool directed);
extern "C" SEXP _igraphlite_graph_create(SEXP edges, SEXP n, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_create(cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(edges), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}
// generators.cpp
IGraph graph_star(int n, int mode, int center);
extern "C" SEXP _igraphlite_graph_star(SEXP n, SEXP mode, SEXP center) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_star(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(mode), cpp11::as_cpp<cpp11::decay_t<int>>(center)));
  END_CPP11
}
// generators.cpp
IGraph graph_lattice(const cpp11::doubles& dim, int nei, bool directed, bool mutual, bool circular);
extern "C" SEXP _igraphlite_graph_lattice(SEXP dim, SEXP nei, SEXP directed, SEXP mutual, SEXP circular) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_lattice(cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(dim), cpp11::as_cpp<cpp11::decay_t<int>>(nei), cpp11::as_cpp<cpp11::decay_t<bool>>(directed), cpp11::as_cpp<cpp11::decay_t<bool>>(mutual), cpp11::as_cpp<cpp11::decay_t<bool>>(circular)));
  END_CPP11
}
// generators.cpp
IGraph graph_ring(int n, bool directed, bool mutual, bool circular);
extern "C" SEXP _igraphlite_graph_ring(SEXP n, SEXP directed, SEXP mutual, SEXP circular) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_ring(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<bool>>(directed), cpp11::as_cpp<cpp11::decay_t<bool>>(mutual), cpp11::as_cpp<cpp11::decay_t<bool>>(circular)));
  END_CPP11
}
// generators.cpp
IGraph graph_tree(int n, int children, int mode);
extern "C" SEXP _igraphlite_graph_tree(SEXP n, SEXP children, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_tree(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(children), cpp11::as_cpp<cpp11::decay_t<int>>(mode)));
  END_CPP11
}
// generators.cpp
IGraph graph_full(int n, bool directed, bool mutual);
extern "C" SEXP _igraphlite_graph_full(SEXP n, SEXP directed, SEXP mutual) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_full(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<bool>>(directed), cpp11::as_cpp<cpp11::decay_t<bool>>(mutual)));
  END_CPP11
}
// generators.cpp
IGraph graph_famous(const char* name);
extern "C" SEXP _igraphlite_graph_famous(SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(graph_famous(cpp11::as_cpp<cpp11::decay_t<const char*>>(name)));
  END_CPP11
}
// init.cpp
cpp11::strings igraph_version();
extern "C" SEXP _igraphlite_igraph_version() {
  BEGIN_CPP11
    return cpp11::as_sexp(igraph_version());
  END_CPP11
}
// init.cpp
void rng_seed(long seed);
extern "C" SEXP _igraphlite_rng_seed(SEXP seed) {
  BEGIN_CPP11
    rng_seed(cpp11::as_cpp<cpp11::decay_t<long>>(seed));
    return R_NilValue;
  END_CPP11
}
// structural.cpp
cpp11::integers path_length_count_within(const IGraph& graph, const cpp11::doubles& vids, bool directed);
extern "C" SEXP _igraphlite_path_length_count_within(SEXP graph, SEXP vids, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(path_length_count_within(cpp11::as_cpp<cpp11::decay_t<const IGraph&>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(vids), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}
// structural.cpp
cpp11::integers path_length_count_between(const IGraph& graph, const cpp11::doubles& from, const cpp11::doubles& to, bool directed);
extern "C" SEXP _igraphlite_path_length_count_between(SEXP graph, SEXP from, SEXP to, SEXP directed) {
  BEGIN_CPP11
    return cpp11::as_sexp(path_length_count_between(cpp11::as_cpp<cpp11::decay_t<const IGraph&>>(graph), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(from), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(to), cpp11::as_cpp<cpp11::decay_t<bool>>(directed)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _igraphlite_graph_create(SEXP, SEXP, SEXP);
extern SEXP _igraphlite_graph_famous(SEXP);
extern SEXP _igraphlite_graph_from_data_frame(SEXP, SEXP);
extern SEXP _igraphlite_graph_from_edgelist(SEXP, SEXP);
extern SEXP _igraphlite_graph_from_symbolic_edgelist(SEXP, SEXP);
extern SEXP _igraphlite_graph_full(SEXP, SEXP, SEXP);
extern SEXP _igraphlite_graph_lattice(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _igraphlite_graph_ring(SEXP, SEXP, SEXP, SEXP);
extern SEXP _igraphlite_graph_star(SEXP, SEXP, SEXP);
extern SEXP _igraphlite_graph_tree(SEXP, SEXP, SEXP);
extern SEXP _igraphlite_igraph_version();
extern SEXP _igraphlite_path_length_count_between(SEXP, SEXP, SEXP, SEXP);
extern SEXP _igraphlite_path_length_count_within(SEXP, SEXP, SEXP);
extern SEXP _igraphlite_rng_seed(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_igraphlite_graph_create",                 (DL_FUNC) &_igraphlite_graph_create,                 3},
    {"_igraphlite_graph_famous",                 (DL_FUNC) &_igraphlite_graph_famous,                 1},
    {"_igraphlite_graph_from_data_frame",        (DL_FUNC) &_igraphlite_graph_from_data_frame,        2},
    {"_igraphlite_graph_from_edgelist",          (DL_FUNC) &_igraphlite_graph_from_edgelist,          2},
    {"_igraphlite_graph_from_symbolic_edgelist", (DL_FUNC) &_igraphlite_graph_from_symbolic_edgelist, 2},
    {"_igraphlite_graph_full",                   (DL_FUNC) &_igraphlite_graph_full,                   3},
    {"_igraphlite_graph_lattice",                (DL_FUNC) &_igraphlite_graph_lattice,                5},
    {"_igraphlite_graph_ring",                   (DL_FUNC) &_igraphlite_graph_ring,                   4},
    {"_igraphlite_graph_star",                   (DL_FUNC) &_igraphlite_graph_star,                   3},
    {"_igraphlite_graph_tree",                   (DL_FUNC) &_igraphlite_graph_tree,                   3},
    {"_igraphlite_igraph_version",               (DL_FUNC) &_igraphlite_igraph_version,               0},
    {"_igraphlite_path_length_count_between",    (DL_FUNC) &_igraphlite_path_length_count_between,    4},
    {"_igraphlite_path_length_count_within",     (DL_FUNC) &_igraphlite_path_length_count_within,     3},
    {"_igraphlite_rng_seed",                     (DL_FUNC) &_igraphlite_rng_seed,                     1},
    {NULL, NULL, 0}
};
}

extern "C" void R_init_igraphlite(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
