# Generated by cpp11: do not edit by hand

graph_from_data_frame <- function(df, directed) {
  .Call("_igraphlite_graph_from_data_frame", df, directed)
}

graph_from_edgelist <- function(edgelist, directed) {
  .Call("_igraphlite_graph_from_edgelist", edgelist, directed)
}

graph_create <- function(edges, n, directed) {
  .Call("_igraphlite_graph_create", edges, n, directed)
}

graph_star <- function(n, mode, center) {
  .Call("_igraphlite_graph_star", n, mode, center)
}

graph_lattice <- function(dim, nei, directed, mutual, circular) {
  .Call("_igraphlite_graph_lattice", dim, nei, directed, mutual, circular)
}

graph_ring <- function(n, directed, mutual, circular) {
  .Call("_igraphlite_graph_ring", n, directed, mutual, circular)
}

graph_tree <- function(n, children, mode) {
  .Call("_igraphlite_graph_tree", n, children, mode)
}

graph_full <- function(n, directed, mutual) {
  .Call("_igraphlite_graph_full", n, directed, mutual)
}

graph_famous <- function(name) {
  .Call("_igraphlite_graph_famous", name)
}

igraph_version <- function() {
  .Call("_igraphlite_igraph_version")
}

rng_seed <- function(seed) {
  invisible(.Call("_igraphlite_rng_seed", seed))
}

path_length_count_within <- function(graph, vids, directed) {
  .Call("_igraphlite_path_length_count_within", graph, vids, directed)
}

path_length_count_between <- function(graph, from, to, directed) {
  .Call("_igraphlite_path_length_count_between", graph, from, to, directed)
}
