# Generated by cpp11: do not edit by hand

V_ <- function(graph) {
  .Call(`_igraphlite_V_`, graph)
}

E_ <- function(graph) {
  .Call(`_igraphlite_E_`, graph)
}

Vnames_ <- function(graph) {
  .Call(`_igraphlite_Vnames_`, graph)
}

from_ <- function(graph) {
  .Call(`_igraphlite_from_`, graph)
}

to_ <- function(graph) {
  .Call(`_igraphlite_to_`, graph)
}

getVattr_ <- function(graph) {
  .Call(`_igraphlite_getVattr_`, graph)
}

getEattr_ <- function(graph) {
  .Call(`_igraphlite_getEattr_`, graph)
}

setVattr_ <- function(graph, other) {
  invisible(.Call(`_igraphlite_setVattr_`, graph, other))
}

setEattr_ <- function(graph, other) {
  invisible(.Call(`_igraphlite_setEattr_`, graph, other))
}

mutate_Vattr_ <- function(graph, key, value) {
  invisible(.Call(`_igraphlite_mutate_Vattr_`, graph, key, value))
}

mutate_Eattr_ <- function(graph, key, value) {
  invisible(.Call(`_igraphlite_mutate_Eattr_`, graph, key, value))
}

graph_empty_ <- function(n, directed) {
  .Call(`_igraphlite_graph_empty_`, n, directed)
}

graph_copy_ <- function(graph) {
  .Call(`_igraphlite_graph_copy_`, graph)
}

vcount_ <- function(graph) {
  .Call(`_igraphlite_vcount_`, graph)
}

ecount_ <- function(graph) {
  .Call(`_igraphlite_ecount_`, graph)
}

is_directed_ <- function(graph) {
  .Call(`_igraphlite_is_directed_`, graph)
}

edge_ <- function(graph, eid) {
  .Call(`_igraphlite_edge_`, graph, eid)
}

neighbors_ <- function(graph, node, mode, loops, multiple) {
  .Call(`_igraphlite_neighbors_`, graph, node, mode, loops, multiple)
}

incident_ <- function(graph, node, mode, loops) {
  .Call(`_igraphlite_incident_`, graph, node, mode, loops)
}

degree_ <- function(graph, vids, mode, loops) {
  .Call(`_igraphlite_degree_`, graph, vids, mode, loops)
}

add_vertices_ <- function(graph, n) {
  invisible(.Call(`_igraphlite_add_vertices_`, graph, n))
}

add_edges_ <- function(graph, edges) {
  invisible(.Call(`_igraphlite_add_edges_`, graph, edges))
}

delete_edges_ <- function(graph, eids) {
  invisible(.Call(`_igraphlite_delete_edges_`, graph, eids))
}

delete_vertices_ <- function(graph, vids) {
  invisible(.Call(`_igraphlite_delete_vertices_`, graph, vids))
}

closeness_ <- function(graph, vids, mode, weights, normalized) {
  .Call(`_igraphlite_closeness_`, graph, vids, mode, weights, normalized)
}

harmonic_centrality_ <- function(graph, vids, mode, weights, normalized) {
  .Call(`_igraphlite_harmonic_centrality_`, graph, vids, mode, weights, normalized)
}

betweenness_ <- function(graph, weights, vids, directed, normalized, cutoff) {
  .Call(`_igraphlite_betweenness_`, graph, weights, vids, directed, normalized, cutoff)
}

betweenness_subset_ <- function(graph, weights, sources, targets, vids, directed, normalized) {
  .Call(`_igraphlite_betweenness_subset_`, graph, weights, sources, targets, vids, directed, normalized)
}

edge_betweenness_ <- function(graph, weights, eids, directed, normalized, cutoff) {
  .Call(`_igraphlite_edge_betweenness_`, graph, weights, eids, directed, normalized, cutoff)
}

edge_betweenness_subset_ <- function(graph, weights, sources, targets, eids, directed, normalized) {
  .Call(`_igraphlite_edge_betweenness_subset_`, graph, weights, sources, targets, eids, directed, normalized)
}

pagerank_ <- function(graph, weights, reset, damping, directed, vids) {
  .Call(`_igraphlite_pagerank_`, graph, weights, reset, damping, directed, vids)
}

constraint_ <- function(graph, vids, weights) {
  .Call(`_igraphlite_constraint_`, graph, vids, weights)
}

eigenvector_centrality_ <- function(graph, mode, weights) {
  .Call(`_igraphlite_eigenvector_centrality_`, graph, mode, weights)
}

hub_and_authority_scores_ <- function(graph, weights) {
  .Call(`_igraphlite_hub_and_authority_scores_`, graph, weights)
}

convergence_degree_ <- function(graph) {
  .Call(`_igraphlite_convergence_degree_`, graph)
}

connected_components_ <- function(graph, mode) {
  .Call(`_igraphlite_connected_components_`, graph, mode)
}

is_connected_ <- function(graph, mode) {
  .Call(`_igraphlite_is_connected_`, graph, mode)
}

count_reachable_ <- function(graph, mode) {
  .Call(`_igraphlite_count_reachable_`, graph, mode)
}

transitive_closure_ <- function(graph) {
  .Call(`_igraphlite_transitive_closure_`, graph)
}

articulation_points_ <- function(graph) {
  .Call(`_igraphlite_articulation_points_`, graph)
}

bridges_ <- function(graph) {
  .Call(`_igraphlite_bridges_`, graph)
}

is_biconnected_ <- function(graph) {
  .Call(`_igraphlite_is_biconnected_`, graph)
}

as_adjlist_ <- function(graph, mode, loops, multiple) {
  .Call(`_igraphlite_as_adjlist_`, graph, mode, loops, multiple)
}

as_inclist_ <- function(graph, mode, loops) {
  .Call(`_igraphlite_as_inclist_`, graph, mode, loops)
}

as_edgelist_ <- function(graph) {
  .Call(`_igraphlite_as_edgelist_`, graph)
}

as_data_frame_ <- function(graph) {
  .Call(`_igraphlite_as_data_frame_`, graph)
}

read_graph_edgelist_ <- function(path, directed) {
  .Call(`_igraphlite_read_graph_edgelist_`, path, directed)
}

write_graph_edgelist_ <- function(graph, path) {
  .Call(`_igraphlite_write_graph_edgelist_`, graph, path)
}

read_graph_ncol_ <- function(path, names, directed) {
  .Call(`_igraphlite_read_graph_ncol_`, path, names, directed)
}

write_graph_ncol_ <- function(graph, path) {
  .Call(`_igraphlite_write_graph_ncol_`, graph, path)
}

read_graph_lgl_ <- function(path, names, directed) {
  .Call(`_igraphlite_read_graph_lgl_`, path, names, directed)
}

write_graph_lgl_ <- function(graph, path, isolates) {
  .Call(`_igraphlite_write_graph_lgl_`, graph, path, isolates)
}

read_graph_graphml_ <- function(path, index) {
  .Call(`_igraphlite_read_graph_graphml_`, path, index)
}

write_graph_graphml_ <- function(graph, path, prefixattr) {
  .Call(`_igraphlite_write_graph_graphml_`, graph, path, prefixattr)
}

read_graph_gml_ <- function(path) {
  .Call(`_igraphlite_read_graph_gml_`, path)
}

write_graph_gml_ <- function(graph, path, creator) {
  .Call(`_igraphlite_write_graph_gml_`, graph, path, creator)
}

read_graph_pajek_ <- function(path) {
  .Call(`_igraphlite_read_graph_pajek_`, path)
}

write_graph_pajek_ <- function(graph, path) {
  .Call(`_igraphlite_write_graph_pajek_`, graph, path)
}

read_graph_dl_ <- function(path, directed) {
  .Call(`_igraphlite_read_graph_dl_`, path, directed)
}

write_graph_dot_ <- function(graph, path) {
  .Call(`_igraphlite_write_graph_dot_`, graph, path)
}

write_graph_leda_ <- function(graph, path) {
  .Call(`_igraphlite_write_graph_leda_`, graph, path)
}

graph_create_ <- function(edges, n, directed) {
  .Call(`_igraphlite_graph_create_`, edges, n, directed)
}

graph_star_ <- function(n, mode, center) {
  .Call(`_igraphlite_graph_star_`, n, mode, center)
}

graph_square_lattice_ <- function(dim, nei, directed, mutual, circular) {
  .Call(`_igraphlite_graph_square_lattice_`, dim, nei, directed, mutual, circular)
}

graph_ring_ <- function(n, directed, mutual, circular) {
  .Call(`_igraphlite_graph_ring_`, n, directed, mutual, circular)
}

graph_kary_tree_ <- function(n, children, mode) {
  .Call(`_igraphlite_graph_kary_tree_`, n, children, mode)
}

graph_full_ <- function(n, directed, loops) {
  .Call(`_igraphlite_graph_full_`, n, directed, loops)
}

graph_famous_ <- function(name) {
  .Call(`_igraphlite_graph_famous_`, name)
}

graph_from_edgelist_ <- function(edgelist, directed) {
  .Call(`_igraphlite_graph_from_edgelist_`, edgelist, directed)
}

graph_from_data_frame_ <- function(df, directed) {
  .Call(`_igraphlite_graph_from_data_frame_`, df, directed)
}

graph_from_symbolic_edgelist_ <- function(edgelist, directed) {
  .Call(`_igraphlite_graph_from_symbolic_edgelist_`, edgelist, directed)
}

graph_from_symbolic_edges_ <- function(edges, directed) {
  .Call(`_igraphlite_graph_from_symbolic_edges_`, edges, directed)
}

igraph_version_ <- function() {
  .Call(`_igraphlite_igraph_version_`)
}

rng_seed <- function(seed) {
  invisible(.Call(`_igraphlite_rng_seed`, seed))
}

layout_random_ <- function(graph) {
  invisible(.Call(`_igraphlite_layout_random_`, graph))
}

layout_drl_ <- function(graph) {
  invisible(.Call(`_igraphlite_layout_drl_`, graph))
}

layout_fruchterman_reingold_ <- function(graph, grid) {
  invisible(.Call(`_igraphlite_layout_fruchterman_reingold_`, graph, grid))
}

layout_mds_ <- function(graph, dist) {
  invisible(.Call(`_igraphlite_layout_mds_`, graph, dist))
}

layout_reingold_tilford_ <- function(graph, mode, roots) {
  invisible(.Call(`_igraphlite_layout_reingold_tilford_`, graph, mode, roots))
}

layout_reingold_tilford_circular_ <- function(graph, mode, roots) {
  invisible(.Call(`_igraphlite_layout_reingold_tilford_circular_`, graph, mode, roots))
}

induced_subgraph_ <- function(graph, vids, impl) {
  .Call(`_igraphlite_induced_subgraph_`, graph, vids, impl)
}

induced_subgraph_edges_ <- function(graph, vids) {
  .Call(`_igraphlite_induced_subgraph_edges_`, graph, vids)
}

subgraph_from_edges_ <- function(graph, eids, delete_vertices) {
  .Call(`_igraphlite_subgraph_from_edges_`, graph, eids, delete_vertices)
}

distances_ <- function(graph, weights, from, to, mode, cutoff) {
  .Call(`_igraphlite_distances_`, graph, weights, from, to, mode, cutoff)
}

get_shortest_paths_ <- function(graph, weights, from, to, mode) {
  .Call(`_igraphlite_get_shortest_paths_`, graph, weights, from, to, mode)
}

get_all_shortest_paths_ <- function(graph, weights, from, to, mode) {
  .Call(`_igraphlite_get_all_shortest_paths_`, graph, weights, from, to, mode)
}

get_all_simple_paths_ <- function(graph, from, to, mode, minlen, maxlen, max_results) {
  .Call(`_igraphlite_get_all_simple_paths_`, graph, from, to, mode, minlen, maxlen, max_results)
}

average_path_length_ <- function(graph, weights, directed, unconn) {
  .Call(`_igraphlite_average_path_length_`, graph, weights, directed, unconn)
}

path_length_hist_ <- function(graph, directed) {
  .Call(`_igraphlite_path_length_hist_`, graph, directed)
}

eccentricity_ <- function(graph, weights, vids, mode) {
  .Call(`_igraphlite_eccentricity_`, graph, weights, vids, mode)
}

diameter_ <- function(graph, weights, directed, unconn) {
  .Call(`_igraphlite_diameter_`, graph, weights, directed, unconn)
}

radius_ <- function(graph, weights, mode) {
  .Call(`_igraphlite_radius_`, graph, weights, mode)
}

mean_distances_cpp_ <- function(graph, from, to, weights, mode, algorithm) {
  .Call(`_igraphlite_mean_distances_cpp_`, graph, from, to, weights, mode, algorithm)
}

path_length_count_within <- function(graph, vids) {
  .Call(`_igraphlite_path_length_count_within`, graph, vids)
}

path_length_count_between <- function(graph, from, to) {
  .Call(`_igraphlite_path_length_count_between`, graph, from, to)
}

are_adjacent_ <- function(graph, v1, v2) {
  .Call(`_igraphlite_are_adjacent_`, graph, v1, v2)
}

is_simple_ <- function(graph, directed) {
  .Call(`_igraphlite_is_simple_`, graph, directed)
}

has_loop_ <- function(graph) {
  .Call(`_igraphlite_has_loop_`, graph)
}

count_loops_ <- function(graph) {
  .Call(`_igraphlite_count_loops_`, graph)
}

has_multiple_ <- function(graph) {
  .Call(`_igraphlite_has_multiple_`, graph)
}

count_multiple_ <- function(graph, eids) {
  .Call(`_igraphlite_count_multiple_`, graph, eids)
}

girth_ <- function(graph) {
  .Call(`_igraphlite_girth_`, graph)
}

neighborhood_size_ <- function(graph, vids, order, mode, mindist) {
  .Call(`_igraphlite_neighborhood_size_`, graph, vids, order, mode, mindist)
}

neighborhood_ <- function(graph, vids, order, mode, mindist) {
  .Call(`_igraphlite_neighborhood_`, graph, vids, order, mode, mindist)
}

subcomponent_ <- function(graph, v, mode) {
  .Call(`_igraphlite_subcomponent_`, graph, v, mode)
}

maxdegree_ <- function(graph, vids, mode, loops) {
  .Call(`_igraphlite_maxdegree_`, graph, vids, mode, loops)
}

strength_ <- function(graph, vids, mode, loops, weights) {
  .Call(`_igraphlite_strength_`, graph, vids, mode, loops, weights)
}

subcomponents_ <- function(graph, vids, mode) {
  .Call(`_igraphlite_subcomponents_`, graph, vids, mode)
}
