# Generated by cpp11: do not edit by hand

V_ <- function(graph) {
  .Call(`_igraphlite_V_`, graph)
}

E_ <- function(graph) {
  .Call(`_igraphlite_E_`, graph)
}

Vnames_ <- function(graph) {
  .Call(`_igraphlite_Vnames_`, graph)
}

from_ <- function(graph) {
  .Call(`_igraphlite_from_`, graph)
}

to_ <- function(graph) {
  .Call(`_igraphlite_to_`, graph)
}

getVattr_ <- function(graph) {
  .Call(`_igraphlite_getVattr_`, graph)
}

getEattr_ <- function(graph) {
  .Call(`_igraphlite_getEattr_`, graph)
}

setVattr_ <- function(graph, other) {
  invisible(.Call(`_igraphlite_setVattr_`, graph, other))
}

setEattr_ <- function(graph, other) {
  invisible(.Call(`_igraphlite_setEattr_`, graph, other))
}

mutate_Vattr_ <- function(graph, key, value) {
  invisible(.Call(`_igraphlite_mutate_Vattr_`, graph, key, value))
}

mutate_Eattr_ <- function(graph, key, value) {
  invisible(.Call(`_igraphlite_mutate_Eattr_`, graph, key, value))
}

graph_empty_ <- function(n, directed) {
  .Call(`_igraphlite_graph_empty_`, n, directed)
}

graph_copy_ <- function(graph) {
  .Call(`_igraphlite_graph_copy_`, graph)
}

vcount_ <- function(graph) {
  .Call(`_igraphlite_vcount_`, graph)
}

ecount_ <- function(graph) {
  .Call(`_igraphlite_ecount_`, graph)
}

is_directed_ <- function(graph) {
  .Call(`_igraphlite_is_directed_`, graph)
}

edge_ <- function(graph, eid) {
  .Call(`_igraphlite_edge_`, graph, eid)
}

edges_ <- function(graph, eids, bycol) {
  .Call(`_igraphlite_edges_`, graph, eids, bycol)
}

get_eids_ <- function(graph, pairs, directed, error) {
  .Call(`_igraphlite_get_eids_`, graph, pairs, directed, error)
}

get_all_eids_between_ <- function(graph, from, to, directed) {
  .Call(`_igraphlite_get_all_eids_between_`, graph, from, to, directed)
}

neighbors_ <- function(graph, node, mode, loops, multiple) {
  .Call(`_igraphlite_neighbors_`, graph, node, mode, loops, multiple)
}

incident_ <- function(graph, node, mode, loops) {
  .Call(`_igraphlite_incident_`, graph, node, mode, loops)
}

degree_ <- function(graph, vids, mode, loops) {
  .Call(`_igraphlite_degree_`, graph, vids, mode, loops)
}

is_same_graph_ <- function(graph1, graph2) {
  .Call(`_igraphlite_is_same_graph_`, graph1, graph2)
}

add_vertices_ <- function(graph, n) {
  invisible(.Call(`_igraphlite_add_vertices_`, graph, n))
}

add_edges_ <- function(graph, edges) {
  invisible(.Call(`_igraphlite_add_edges_`, graph, edges))
}

delete_edges_ <- function(graph, eids) {
  invisible(.Call(`_igraphlite_delete_edges_`, graph, eids))
}

delete_vertices_ <- function(graph, vids) {
  invisible(.Call(`_igraphlite_delete_vertices_`, graph, vids))
}

VCOUNT_MAX <- function() {
  .Call(`_igraphlite_VCOUNT_MAX`)
}

ECOUNT_MAX <- function() {
  .Call(`_igraphlite_ECOUNT_MAX`)
}

UNLIMITED <- function() {
  .Call(`_igraphlite_UNLIMITED`)
}

closeness_ <- function(graph, vids, mode, weights, normalized) {
  .Call(`_igraphlite_closeness_`, graph, vids, mode, weights, normalized)
}

harmonic_centrality_ <- function(graph, vids, mode, weights, normalized) {
  .Call(`_igraphlite_harmonic_centrality_`, graph, vids, mode, weights, normalized)
}

betweenness_ <- function(graph, weights, vids, directed, normalized, cutoff) {
  .Call(`_igraphlite_betweenness_`, graph, weights, vids, directed, normalized, cutoff)
}

betweenness_subset_ <- function(graph, weights, sources, targets, vids, directed, normalized) {
  .Call(`_igraphlite_betweenness_subset_`, graph, weights, sources, targets, vids, directed, normalized)
}

edge_betweenness_ <- function(graph, weights, eids, directed, normalized, cutoff) {
  .Call(`_igraphlite_edge_betweenness_`, graph, weights, eids, directed, normalized, cutoff)
}

edge_betweenness_subset_ <- function(graph, weights, sources, targets, eids, directed, normalized) {
  .Call(`_igraphlite_edge_betweenness_subset_`, graph, weights, sources, targets, eids, directed, normalized)
}

pagerank_ <- function(graph, weights, reset, damping, directed, vids) {
  .Call(`_igraphlite_pagerank_`, graph, weights, reset, damping, directed, vids)
}

constraint_ <- function(graph, vids, weights) {
  .Call(`_igraphlite_constraint_`, graph, vids, weights)
}

eigenvector_centrality_ <- function(graph, mode, weights) {
  .Call(`_igraphlite_eigenvector_centrality_`, graph, mode, weights)
}

hub_and_authority_scores_ <- function(graph, weights) {
  .Call(`_igraphlite_hub_and_authority_scores_`, graph, weights)
}

convergence_degree_ <- function(graph) {
  .Call(`_igraphlite_convergence_degree_`, graph)
}

cliques_ <- function(graph, min_size, max_size, max_results) {
  .Call(`_igraphlite_cliques_`, graph, min_size, max_size, max_results)
}

clique_size_hist_ <- function(graph, min_size, max_size) {
  .Call(`_igraphlite_clique_size_hist_`, graph, min_size, max_size)
}

largest_cliques_ <- function(graph) {
  .Call(`_igraphlite_largest_cliques_`, graph)
}

maximal_cliques_ <- function(graph, min_size, max_size, max_results) {
  .Call(`_igraphlite_maximal_cliques_`, graph, min_size, max_size, max_results)
}

maximal_cliques_count_ <- function(graph, min_size, max_size) {
  .Call(`_igraphlite_maximal_cliques_count_`, graph, min_size, max_size)
}

maximal_cliques_hist_ <- function(graph, min_size, max_size) {
  .Call(`_igraphlite_maximal_cliques_hist_`, graph, min_size, max_size)
}

clique_number_ <- function(graph) {
  .Call(`_igraphlite_clique_number_`, graph)
}

independent_vertex_sets_ <- function(graph, min_size, max_size, max_results) {
  .Call(`_igraphlite_independent_vertex_sets_`, graph, min_size, max_size, max_results)
}

largest_independent_vertex_sets_ <- function(graph) {
  .Call(`_igraphlite_largest_independent_vertex_sets_`, graph)
}

maximal_independent_vertex_sets_ <- function(graph, min_size, max_size, max_results) {
  .Call(`_igraphlite_maximal_independent_vertex_sets_`, graph, min_size, max_size, max_results)
}

independence_number_ <- function(graph) {
  .Call(`_igraphlite_independence_number_`, graph)
}

connected_components_ <- function(graph, mode) {
  .Call(`_igraphlite_connected_components_`, graph, mode)
}

is_connected_ <- function(graph, mode) {
  .Call(`_igraphlite_is_connected_`, graph, mode)
}

count_reachable_ <- function(graph, mode) {
  .Call(`_igraphlite_count_reachable_`, graph, mode)
}

transitive_closure_ <- function(graph) {
  .Call(`_igraphlite_transitive_closure_`, graph)
}

articulation_points_ <- function(graph) {
  .Call(`_igraphlite_articulation_points_`, graph)
}

bridges_ <- function(graph) {
  .Call(`_igraphlite_bridges_`, graph)
}

is_biconnected_ <- function(graph) {
  .Call(`_igraphlite_is_biconnected_`, graph)
}

topological_sorting_ <- function(graph, mode) {
  .Call(`_igraphlite_topological_sorting_`, graph, mode)
}

is_dag_ <- function(graph) {
  .Call(`_igraphlite_is_dag_`, graph)
}

is_eulerian_ <- function(graph) {
  .Call(`_igraphlite_is_eulerian_`, graph)
}

as_adjlist_ <- function(graph, mode, loops, multiple) {
  .Call(`_igraphlite_as_adjlist_`, graph, mode, loops, multiple)
}

as_inclist_ <- function(graph, mode, loops) {
  .Call(`_igraphlite_as_inclist_`, graph, mode, loops)
}

as_edgelist_ <- function(graph) {
  .Call(`_igraphlite_as_edgelist_`, graph)
}

as_data_frame_ <- function(graph) {
  .Call(`_igraphlite_as_data_frame_`, graph)
}

read_graph_edgelist_ <- function(path, directed) {
  .Call(`_igraphlite_read_graph_edgelist_`, path, directed)
}

write_graph_edgelist_ <- function(graph, path) {
  .Call(`_igraphlite_write_graph_edgelist_`, graph, path)
}

read_graph_ncol_ <- function(path, names, directed) {
  .Call(`_igraphlite_read_graph_ncol_`, path, names, directed)
}

write_graph_ncol_ <- function(graph, path) {
  .Call(`_igraphlite_write_graph_ncol_`, graph, path)
}

read_graph_lgl_ <- function(path, names, directed) {
  .Call(`_igraphlite_read_graph_lgl_`, path, names, directed)
}

write_graph_lgl_ <- function(graph, path, isolates) {
  .Call(`_igraphlite_write_graph_lgl_`, graph, path, isolates)
}

read_graph_graphml_ <- function(path, index) {
  .Call(`_igraphlite_read_graph_graphml_`, path, index)
}

write_graph_graphml_ <- function(graph, path, prefixattr) {
  .Call(`_igraphlite_write_graph_graphml_`, graph, path, prefixattr)
}

read_graph_gml_ <- function(path) {
  .Call(`_igraphlite_read_graph_gml_`, path)
}

write_graph_gml_ <- function(graph, path, creator) {
  .Call(`_igraphlite_write_graph_gml_`, graph, path, creator)
}

read_graph_pajek_ <- function(path) {
  .Call(`_igraphlite_read_graph_pajek_`, path)
}

write_graph_pajek_ <- function(graph, path) {
  .Call(`_igraphlite_write_graph_pajek_`, graph, path)
}

read_graph_dl_ <- function(path, directed) {
  .Call(`_igraphlite_read_graph_dl_`, path, directed)
}

write_graph_dot_ <- function(graph, path) {
  .Call(`_igraphlite_write_graph_dot_`, graph, path)
}

write_graph_leda_ <- function(graph, path) {
  .Call(`_igraphlite_write_graph_leda_`, graph, path)
}

erdos_renyi_game_gnm_ <- function(n, m, directed, edge_type_sw) {
  .Call(`_igraphlite_erdos_renyi_game_gnm_`, n, m, directed, edge_type_sw)
}

erdos_renyi_game_gnp_ <- function(n, p_, directed, edge_type_sw) {
  .Call(`_igraphlite_erdos_renyi_game_gnp_`, n, p_, directed, edge_type_sw)
}

degree_sequence_game_ <- function(out_degrees, in_degrees, method) {
  .Call(`_igraphlite_degree_sequence_game_`, out_degrees, in_degrees, method)
}

k_regular_game_ <- function(n, k, directed, multiple) {
  .Call(`_igraphlite_k_regular_game_`, n, k, directed, multiple)
}

watts_strogatz_game_ <- function(dim, size, nei, prob, edge_type_sw) {
  .Call(`_igraphlite_watts_strogatz_game_`, dim, size, nei, prob, edge_type_sw)
}

rewire_edges_ <- function(graph, prob, edge_type_sw) {
  invisible(.Call(`_igraphlite_rewire_edges_`, graph, prob, edge_type_sw))
}

graph_create_ <- function(edges, n, directed) {
  .Call(`_igraphlite_graph_create_`, edges, n, directed)
}

graph_star_ <- function(n, mode, center) {
  .Call(`_igraphlite_graph_star_`, n, mode, center)
}

graph_hypercube_ <- function(n, directed) {
  .Call(`_igraphlite_graph_hypercube_`, n, directed)
}

graph_square_lattice_ <- function(dim, nei, directed, mutual, circular) {
  .Call(`_igraphlite_graph_square_lattice_`, dim, nei, directed, mutual, circular)
}

graph_triangular_lattice_ <- function(dims, directed, mutual) {
  .Call(`_igraphlite_graph_triangular_lattice_`, dims, directed, mutual)
}

graph_hexagonal_lattice_ <- function(dims, directed, mutual) {
  .Call(`_igraphlite_graph_hexagonal_lattice_`, dims, directed, mutual)
}

graph_ring_ <- function(n, directed, mutual, circular) {
  .Call(`_igraphlite_graph_ring_`, n, directed, mutual, circular)
}

graph_lcf_ <- function(n, shifts, repeats) {
  .Call(`_igraphlite_graph_lcf_`, n, shifts, repeats)
}

graph_circulant_ <- function(n, shifts, directed) {
  .Call(`_igraphlite_graph_circulant_`, n, shifts, directed)
}

graph_kary_tree_ <- function(n, children, mode) {
  .Call(`_igraphlite_graph_kary_tree_`, n, children, mode)
}

graph_full_ <- function(n, directed, loops) {
  .Call(`_igraphlite_graph_full_`, n, directed, loops)
}

graph_famous_ <- function(name) {
  .Call(`_igraphlite_graph_famous_`, name)
}

graph_from_edgelist_ <- function(edgelist, directed) {
  .Call(`_igraphlite_graph_from_edgelist_`, edgelist, directed)
}

graph_from_data_frame_ <- function(df, directed) {
  .Call(`_igraphlite_graph_from_data_frame_`, df, directed)
}

graph_from_symbolic_edgelist_ <- function(edgelist, directed) {
  .Call(`_igraphlite_graph_from_symbolic_edgelist_`, edgelist, directed)
}

graph_from_symbolic_edges_ <- function(edges, directed) {
  .Call(`_igraphlite_graph_from_symbolic_edges_`, edges, directed)
}

igraph_version_ <- function() {
  .Call(`_igraphlite_igraph_version_`)
}

rng_seed <- function(seed) {
  invisible(.Call(`_igraphlite_rng_seed`, seed))
}

isomorphic_ <- function(graph1, graph2) {
  .Call(`_igraphlite_isomorphic_`, graph1, graph2)
}

subisomorphic_ <- function(graph1, graph2) {
  .Call(`_igraphlite_subisomorphic_`, graph1, graph2)
}

canonical_permutation_ <- function(graph, colors) {
  .Call(`_igraphlite_canonical_permutation_`, graph, colors)
}

layout_random_ <- function(graph) {
  invisible(.Call(`_igraphlite_layout_random_`, graph))
}

layout_circle_ <- function(graph, order) {
  invisible(.Call(`_igraphlite_layout_circle_`, graph, order))
}

layout_star_ <- function(graph, center, order) {
  invisible(.Call(`_igraphlite_layout_star_`, graph, center, order))
}

layout_grid_ <- function(graph, width) {
  invisible(.Call(`_igraphlite_layout_grid_`, graph, width))
}

layout_drl_ <- function(graph) {
  invisible(.Call(`_igraphlite_layout_drl_`, graph))
}

layout_fruchterman_reingold_ <- function(graph, grid) {
  invisible(.Call(`_igraphlite_layout_fruchterman_reingold_`, graph, grid))
}

layout_mds_ <- function(graph, dist) {
  invisible(.Call(`_igraphlite_layout_mds_`, graph, dist))
}

layout_reingold_tilford_ <- function(graph, mode, roots) {
  invisible(.Call(`_igraphlite_layout_reingold_tilford_`, graph, mode, roots))
}

layout_reingold_tilford_circular_ <- function(graph, mode, roots) {
  invisible(.Call(`_igraphlite_layout_reingold_tilford_circular_`, graph, mode, roots))
}

neighborhood_size_ <- function(graph, vids, order, mode, mindist) {
  .Call(`_igraphlite_neighborhood_size_`, graph, vids, order, mode, mindist)
}

neighborhood_ <- function(graph, vids, order, mode, mindist) {
  .Call(`_igraphlite_neighborhood_`, graph, vids, order, mode, mindist)
}

rewire_ <- function(graph, n, edge_type_sw) {
  invisible(.Call(`_igraphlite_rewire_`, graph, n, edge_type_sw))
}

induced_subgraph_ <- function(graph, vids, impl) {
  .Call(`_igraphlite_induced_subgraph_`, graph, vids, impl)
}

induced_subgraph_edges_ <- function(graph, vids) {
  .Call(`_igraphlite_induced_subgraph_edges_`, graph, vids)
}

subgraph_from_edges_ <- function(graph, eids, delete_vertices) {
  .Call(`_igraphlite_subgraph_from_edges_`, graph, eids, delete_vertices)
}

permute_vertices_ <- function(graph, perm) {
  .Call(`_igraphlite_permute_vertices_`, graph, perm)
}

distances_ <- function(graph, weights, from, to, mode, cutoff) {
  .Call(`_igraphlite_distances_`, graph, weights, from, to, mode, cutoff)
}

get_shortest_paths_ <- function(graph, weights, from, to, mode) {
  .Call(`_igraphlite_get_shortest_paths_`, graph, weights, from, to, mode)
}

get_all_shortest_paths_ <- function(graph, weights, from, to, mode) {
  .Call(`_igraphlite_get_all_shortest_paths_`, graph, weights, from, to, mode)
}

get_all_simple_paths_ <- function(graph, from, to, mode, minlen, maxlen, max_results) {
  .Call(`_igraphlite_get_all_simple_paths_`, graph, from, to, mode, minlen, maxlen, max_results)
}

average_path_length_ <- function(graph, weights, directed, unconn) {
  .Call(`_igraphlite_average_path_length_`, graph, weights, directed, unconn)
}

path_length_hist_ <- function(graph, directed) {
  .Call(`_igraphlite_path_length_hist_`, graph, directed)
}

eccentricity_ <- function(graph, weights, vids, mode) {
  .Call(`_igraphlite_eccentricity_`, graph, weights, vids, mode)
}

diameter_ <- function(graph, weights, directed, unconn) {
  .Call(`_igraphlite_diameter_`, graph, weights, directed, unconn)
}

radius_ <- function(graph, weights, mode) {
  .Call(`_igraphlite_radius_`, graph, weights, mode)
}

global_efficiency_ <- function(graph, weights, directed) {
  .Call(`_igraphlite_global_efficiency_`, graph, weights, directed)
}

local_efficiency_ <- function(graph, weights, vids, directed, mode) {
  .Call(`_igraphlite_local_efficiency_`, graph, weights, vids, directed, mode)
}

average_local_efficiency_ <- function(graph, weights, directed, mode) {
  .Call(`_igraphlite_average_local_efficiency_`, graph, weights, directed, mode)
}

expand_path_to_pairs_ <- function(path) {
  .Call(`_igraphlite_expand_path_to_pairs_`, path)
}

mean_distances_cpp_ <- function(graph, weights, from, to, mode) {
  .Call(`_igraphlite_mean_distances_cpp_`, graph, weights, from, to, mode)
}

path_length_count_within <- function(graph, vids) {
  .Call(`_igraphlite_path_length_count_within`, graph, vids)
}

path_length_count_between <- function(graph, from, to) {
  .Call(`_igraphlite_path_length_count_between`, graph, from, to)
}

are_adjacent_ <- function(graph, v1, v2) {
  .Call(`_igraphlite_are_adjacent_`, graph, v1, v2)
}

is_simple_ <- function(graph, directed) {
  .Call(`_igraphlite_is_simple_`, graph, directed)
}

is_acyclic_ <- function(graph) {
  .Call(`_igraphlite_is_acyclic_`, graph)
}

has_loop_ <- function(graph) {
  .Call(`_igraphlite_has_loop_`, graph)
}

count_loops_ <- function(graph) {
  .Call(`_igraphlite_count_loops_`, graph)
}

has_multiple_ <- function(graph) {
  .Call(`_igraphlite_has_multiple_`, graph)
}

count_multiple_ <- function(graph, eids) {
  .Call(`_igraphlite_count_multiple_`, graph, eids)
}

girth_ <- function(graph) {
  .Call(`_igraphlite_girth_`, graph)
}

maxdegree_ <- function(graph, vids, mode, loops) {
  .Call(`_igraphlite_maxdegree_`, graph, vids, mode, loops)
}

strength_ <- function(graph, vids, mode, loops, weights) {
  .Call(`_igraphlite_strength_`, graph, vids, mode, loops, weights)
}

is_complete_ <- function(graph) {
  .Call(`_igraphlite_is_complete_`, graph)
}

is_clique_ <- function(graph, candidate, directed) {
  .Call(`_igraphlite_is_clique_`, graph, candidate, directed)
}

is_independent_vertex_set_ <- function(graph, candidate) {
  .Call(`_igraphlite_is_independent_vertex_set_`, graph, candidate)
}

subcomponent_ <- function(graph, v, mode) {
  .Call(`_igraphlite_subcomponent_`, graph, v, mode)
}

subcomponents_ <- function(graph, vids, mode) {
  .Call(`_igraphlite_subcomponents_`, graph, vids, mode)
}
