# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edgelist <- function(graph) {
    .Call(`_igraphlite_edgelist`, graph)
}

make_empty_graph <- function(n, directed = TRUE) {
    .Call(`_igraphlite_make_empty_graph`, n, directed)
}

make_graph <- function(edges, n = 0L, directed = TRUE) {
    .Call(`_igraphlite_make_graph`, edges, n, directed)
}

make_tree <- function(n, children = 2L, mode = 0L) {
    .Call(`_igraphlite_make_tree`, n, children, mode)
}

impl_degree_all <- function(graph, mode = 3L, loops = TRUE) {
    .Call(`_igraphlite_impl_degree_all`, graph, mode, loops)
}

impl_degree <- function(graph, vs, mode = 3L, loops = TRUE) {
    .Call(`_igraphlite_impl_degree`, graph, vs, mode, loops)
}

get_gan <- function(graph, name) {
    .Call(`_igraphlite_get_gan`, graph, name)
}

get_gas <- function(graph, name) {
    .Call(`_igraphlite_get_gas`, graph, name)
}

set_gattr <- function(graph, name, value) {
    invisible(.Call(`_igraphlite_set_gattr`, graph, name, value))
}

get_van <- function(graph, name) {
    .Call(`_igraphlite_get_van`, graph, name)
}

get_vas <- function(graph, name) {
    .Call(`_igraphlite_get_vas`, graph, name)
}

set_vattr <- function(graph, name, values) {
    invisible(.Call(`_igraphlite_set_vattr`, graph, name, values))
}

len <- function(args) {
    .Call(`_igraphlite_len`, args)
}

