# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

graph_from_symbolic_edgelist <- function(edgelist, directed = TRUE) {
    .Call(`_igraphlite_graph_from_symbolic_edgelist`, edgelist, directed)
}

graph_from_edgelist <- function(edgelist, directed = TRUE) {
    .Call(`_igraphlite_graph_from_edgelist`, edgelist, directed)
}

graph_create <- function(edges, n = 0L, directed = TRUE) {
    .Call(`_igraphlite_graph_create`, edges, n, directed)
}

graph_tree <- function(n, children = 2L, mode = 0L) {
    .Call(`_igraphlite_graph_tree`, n, children, mode)
}

