# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vcount_ <- function(graph) {
    .Call(`_igraphlite_vcount_`, graph)
}

ecount_ <- function(graph) {
    .Call(`_igraphlite_ecount_`, graph)
}

#' @param df data.frame that includes an edgelist and edge attributes.
#' @param edgelist Two-column matrix.
#' @param directed Boolean
#' @rdname as_igraph
#' @export
graph_from_data_frame <- function(df, directed = TRUE) {
    .Call(`_igraphlite_graph_from_data_frame`, df, directed)
}

#' @rdname as_igraph
#' @export
graph_from_symbolic_edgelist <- function(edgelist, directed = TRUE) {
    .Call(`_igraphlite_graph_from_symbolic_edgelist`, edgelist, directed)
}

#' @rdname as_igraph
#' @export
graph_from_edgelist <- function(edgelist, directed = TRUE) {
    .Call(`_igraphlite_graph_from_edgelist`, edgelist, directed)
}

#' Deterministic Graph Generators
#'
#' @param edges The edges to add, the first two elements are the first edge, etc.
#' @param n Integer, the number of vertices in the graph.
#' @param directed Boolean
#' @param mutual Boolean
#' @param circular Boolean
#' @param mode Integer;
#'   - `igraph_star_mode_t` \{0: OUT, 1: IN, 2: MUTUAL, 3: UNDIRECTED\}
#'   - `igraph_tree_mode_t` \{0: OUT, 1: IN, 2: UNDIRECTED\}
#' @seealso [as_igraph()], [graph_from_data_frame()]
#' @source <https://igraph.org/c/doc/igraph-Generators.html>
#' @rdname generators
#' @export
graph_create <- function(edges, n = 0L, directed = TRUE) {
    .Call(`_igraphlite_graph_create`, edges, n, directed)
}

#' @param center Id of the vertex which will be the center of the graph.
#' @rdname generators
#' @export
graph_star <- function(n, mode = 0L, center = 1L) {
    .Call(`_igraphlite_graph_star`, n, mode, center)
}

#' @param dim Vector giving the sizes of the lattice in each of its dimensions.
#' @param nei Integer distance within which two vertices will be connected.
#' @rdname generators
#' @export
graph_lattice <- function(dim, nei = 1L, directed = FALSE, mutual = FALSE, circular = FALSE) {
    .Call(`_igraphlite_graph_lattice`, dim, nei, directed, mutual, circular)
}

#' @rdname generators
#' @export
graph_ring <- function(n, directed = FALSE, mutual = FALSE, circular = TRUE) {
    .Call(`_igraphlite_graph_ring`, n, directed, mutual, circular)
}

#' @param children Integer, the number of children of a vertex in the tree.
#' @rdname generators
#' @export
graph_tree <- function(n, children = 2L, mode = 0L) {
    .Call(`_igraphlite_graph_tree`, n, children, mode)
}

#' @rdname generators
#' @export
graph_full <- function(n, directed = FALSE, mutual = FALSE) {
    .Call(`_igraphlite_graph_full`, n, directed, mutual)
}

#' @param name \{Bull, Chvatal, Coxeter, Cubical, Diamond, Dodecahedral,
#'   Dodecahedron, Folkman, Franklin, Frucht, Grotzsch, Heawood, Herschel, House,
#'   HouseX, Icosahedral, Icosahedron, Krackhardt_Kite, Levi, McGee, Meredith,
#'   Noperfectmatching, Nonline, Octahedral, Octahedron, Petersen, Robertson,
#'   Smallestcyclicgroup, Tetrahedral, Tetrahedron, Thomassen, Tutte,
#'   Uniquely3colorable, Walther, Zachary\}
#' @rdname generators
#' @export
graph_famous <- function(name) {
    .Call(`_igraphlite_graph_famous`, name)
}

#' Check and return igraph version.h
#'
#' @source <https://igraph.org/c/doc/igraph-Nongraph.html>
#' @rdname version
#' @export
igraph_version <- function() {
    .Call(`_igraphlite_igraph_version`)
}

#' Random numbers
#'
#' @source <https://igraph.org/c/doc/igraph-Random.html>
#' @param seed An integer.
#' @rdname random
#' @export
rng_seed <- function(seed) {
    invisible(.Call(`_igraphlite_rng_seed`, seed))
}

from_ <- function(graph) {
    .Call(`_igraphlite_from_`, graph)
}

to_ <- function(graph) {
    .Call(`_igraphlite_to_`, graph)
}

path_length_count_within <- function(graph, vids, directed) {
    .Call(`_igraphlite_path_length_count_within`, graph, vids, directed)
}

path_length_count_between <- function(graph, from, to, directed) {
    .Call(`_igraphlite_path_length_count_between`, graph, from, to, directed)
}

